/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrentalsystem.auth;

import javax.swing.*;
import java.awt.*;
import java.net.URL;
/**
 *
 * @author macbookairm1grey
 */
public class LoginFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        //Other setup style
        setSize(1440,1024);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        
        //Pane Glass
        pnlGlass.setOpaque(false);
        pnlGlass.setBackground(new Color(68, 49, 38, 120));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlMainContainer = new BackgroundPanel();
        ;
        pnlGlass = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();

                g2.setColor(getBackground());

                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 50, 50);

                g2.dispose();

                super.paintComponent(g);
            }
        }
        ;
        lblTitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField() {
            {
                // 1. THIS IS THE INTERNAL PADDING (Top, Left, Bottom, Right)
                // 20 pixels on the left will push the text away from the curve
                setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
                setOpaque(false);
                setBackground(new java.awt.Color(0, 0, 0, 0));
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);
                g2.dispose();
                super.paintComponent(g);
            }

            // REMOVED the empty setBorder method that was blocking your changes
        }
        ;
        lblPassword = new javax.swing.JLabel();
        txtPassword = // Change JTextField to JPasswordField here!
        new javax.swing.JPasswordField() {
            {
                setOpaque(false);
                setBackground(new java.awt.Color(0, 0, 0, 0));
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                g2.setColor(java.awt.Color.WHITE);
                g2.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);

                g2.dispose();
                super.paintComponent(g);
            }

        }
        ;
        btnLogin = new javax.swing.JButton() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // Change color slightly when hovering/clicking for a modern feel
                if (getModel().isPressed()) {
                    g2.setColor(new java.awt.Color(50, 50, 50)); // Dark grey when clicked
                } else if (getModel().isRollover()) {
                    g2.setColor(new java.awt.Color(30, 30, 30)); // Slightly lighter black on hover
                } else {
                    g2.setColor(getBackground()); // Default Black
                }

                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30);
                g2.dispose();

                super.paintComponent(g);
            }

            @Override
            public void setBorder(javax.swing.border.Border border) {
                // Prevents square border from appearing
            }
        }
        ;

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pnlMainContainer.setPreferredSize(new java.awt.Dimension(400, 300));
        pnlMainContainer.setLayout(new java.awt.GridBagLayout());

        pnlGlass.setBackground(new java.awt.Color(68, 49, 38));
        pnlGlass.setMinimumSize(new java.awt.Dimension(600, 600));
        pnlGlass.setOpaque(false);
        pnlGlass.setPreferredSize(new java.awt.Dimension(600, 500));
        pnlGlass.setLayout(new java.awt.GridBagLayout());

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 72)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Rent A Car");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(70, 0, 10, 0);
        pnlGlass.add(lblTitle, gridBagConstraints);

        lblUsername.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 5, 0);
        pnlGlass.add(lblUsername, gridBagConstraints);

        txtUsername.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        txtUsername.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        txtUsername.setPreferredSize(new java.awt.Dimension(500, 50));
        txtUsername.addActionListener(this::txtUsernameActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 20, 50);
        pnlGlass.add(txtUsername, gridBagConstraints);

        lblPassword.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 5, 0);
        pnlGlass.add(lblPassword, gridBagConstraints);

        txtPassword.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        txtPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        txtPassword.setPreferredSize(new java.awt.Dimension(500, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        pnlGlass.add(txtPassword, gridBagConstraints);

        btnLogin.setBackground(new java.awt.Color(68, 49, 38));
        btnLogin.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Log In");
        btnLogin.setContentAreaFilled(false);
        btnLogin.setPreferredSize(new java.awt.Dimension(200, 50));
        btnLogin.addActionListener(this::btnLoginActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(30, 50, 10, 20);
        pnlGlass.add(btnLogin, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 100);
        pnlMainContainer.add(pnlGlass, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(pnlMainContainer, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int failedAttempts = 0;
    private carrentalsystem.interfaces.IAuthService authService = new carrentalsystem.services.AuthService();

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
 
        String username = txtUsername.getText().trim();
        String password = new String(txtPassword.getPassword()).trim();

        // ── 1. Empty field guard ──────────────────────────────────
        if (username.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please enter your username and password.",
                    "Login Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // ── 2. Call AuthService ───────────────────────────────────
        try {
            
            if (!authService.usernameExists(username)) {
                int choice = javax.swing.JOptionPane.showConfirmDialog(
                        this,
                        "No account found. Want to Signup a account?",
                        "Account Not Found", 
                javax.swing.JOptionPane.YES_NO_OPTION
            );

            if (choice == javax.swing.JOptionPane.YES_OPTION) {
                
                // Direct to SignupFrame (Ensure SignupFrame class is in your project)
                new carrentalsystem.auth.SignupFrame().setVisible(true);
                this.dispose(); // Close current login window
            }
            return;
        }
            
            
            carrentalsystem.interfaces.IAuthService authService
                    = new carrentalsystem.services.AuthService();

            carrentalsystem.models.User user = authService.login(username, password);

            if (user == null) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Incorrect email or password.",
                        "Login Failed", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // ── 3. Check if account is banned ────────────────────
            if ("BANNED".equals(user.getStatus())) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Your account has been suspended. Contact support.",
                        "Access Denied", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // ── 4. Start session + IdleTracker ───────────────────
            carrentalsystem.core.SessionManager.getInstance().startSession(user);
            new carrentalsystem.utils.IdleTracker().start();

            // ── 5. Route by role ──────────────────────────────────
            if ("ADMIN".equals(user.getRole())) {
                new carrentalsystem.ui.admin.AdminDashboard().setVisible(true);
            } else {
                new carrentalsystem.ui.user.MainDashboard().setVisible(true);
            }

            this.dispose();

        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Database error: " + e.getMessage(),
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }
    
    class BackgroundPanel extends javax.swing.JPanel {
        private Image img;

        public BackgroundPanel() {
            // Use the Project Resource path so it works for your teammates too!
            URL imgURL = getClass().getResource("/carrentalsystem/auth/backgroundloginframe.png");
            if (imgURL != null) {
                this.img = new javax.swing.ImageIcon(imgURL).getImage();
            }
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            if (img != null) {
                // This draws the image to fill the entire panel size
                g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
            }
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlGlass;
    private javax.swing.JPanel pnlMainContainer;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
