/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package carrentalsystem.ui.user;
import carrentalsystem.utils.RoundedBorder;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
/**
 *
 * @author macbookairm1grey
 */
public class AddListPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddListPanel
     */
    
    private MainDashboard dashboard;
    private String selectedImagePath = null;
    private Object txtPrice;
    private int currentEditingCarId;
    
    public AddListPanel() {
        initComponents();
        
        // 1. Set the look of the card
        this.setBackground(java.awt.Color.WHITE);
        this.setOpaque(false); // Allows the MainDashboard nude background to show through corners

        // 2. Apply the Rounded Border (30px radius, subtle grey border)
        // Ensure you have created RoundedBorder.java in carrentalsystem.utils
        this.setBorder(new carrentalsystem.utils.RoundedBorder(30, new java.awt.Color(220, 220, 220), 1));
        
        // Ensure preview is hidden initially
        lblPhotoPreview.setVisible(false);
        
        // This removes the border from the scroll pane itself
        spDescription.setBorder(null);
        spDescription.setOpaque(false);
        spDescription.getViewport().setOpaque(false);
    }
    
    private void clearForm() {
        txtBrand.setText("e.g., Toyota");
        txtModel.setText("e.g., Vios");
        txtBasePrice.setText("");
        txtDescription.setText("Tell renters what makes your car special.");
        lblPhotoPreview.setIcon(null);
        lblPhotoPreview.setVisible(false);
        lblImageIcon.setVisible(true);
        lblUploadText.setVisible(true);
        selectedImagePath = null;
    }
    
    // Inside your AddList panel class (e.g., AddListPanel.java)
    public void prepareEdit(carrentalsystem.models.Car car) {
        // Fill text fields with existing car data
        txtBrand.setText(car.getBrand());
        txtModel.setText(car.getModel());
        txtBasePrice.setText(String.valueOf(car.getBasePrice()));

        // Store the Car ID in a hidden variable to know this is an UPDATE, not a NEW car
        this.currentEditingCarId = car.getCarId();

        // Show the current image
        carrentalsystem.utils.ImageUtil.applyScaledImage(lblPhotoPreview, car.getImagePath(), 300, 200);

        // Change the button text from "Add Car" to "Update Listing"
        btnCreateListing.setText("Update Listing");
    }
    
    public void prepareAdd() {
        this.currentEditingCarId = -1; // CRITICAL: Reset the state[cite: 10]
        clearForm();                   // Wipe the text fields
        btnCreateListing.setText("Create Listing"); // Fix the button label[cite: 10]
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblTitle = new javax.swing.JLabel();
        pnlImageUpload = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(getBackground());
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 20, 20);
                float[] dash = {10.0f, 5.0f};
                g2.setStroke(new java.awt.BasicStroke(2, java.awt.BasicStroke.CAP_BUTT, java.awt.BasicStroke.JOIN_MITER, 10.0f, dash, 0.0f));
                g2.setColor(new java.awt.Color(200, 200, 200));
                g2.drawRoundRect(1, 1, getWidth() - 2, getHeight() - 2, 20, 20);
                g2.dispose();
            }
        };
        lblImageIcon = new javax.swing.JLabel();
        lblUploadText = new javax.swing.JLabel();
        lblPhotoPreview = new javax.swing.JLabel();
        lblGenInfo = new javax.swing.JLabel();
        lblBrand = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField() {
            {
                setOpaque(false);
                setBackground(new java.awt.Color(245, 245, 245)); // Inner capsule color
                setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 50, 5, 15));

                setUI(new javax.swing.plaf.basic.BasicTextFieldUI() {
                    @Override
                    protected void paintBackground(java.awt.Graphics g) {
                        // We handle the background below
                    }
                });
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // 1. FILL THE ENTIRE SQUARE WITH WHITE
                // This matches your JPanel background and "hides" the corners
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRect(0, 0, getWidth(), getHeight());

                // 2. Draw the Grey Capsule on top of the white square
                g2.setColor(getBackground());
                g2.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);

                // 3. Draw the subtle border
                g2.setColor(new java.awt.Color(220, 220, 220));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);

                // 4. Draw the Icon at X=15
                try {
                    java.net.URL imgUrl = getClass().getResource("/carrentalsystem/ui/user/Icons/Car.png");
                    if (imgUrl != null) {
                        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgUrl);
                        g2.drawImage(icon.getImage(), 15, (getHeight() - 20) / 2, 20, 20, null);
                    }
                } catch (Exception e) {}

                g2.dispose();
                super.paintComponent(g);
            }
        };
        lblBasePrice = new javax.swing.JLabel();
        txtBasePrice = new javax.swing.JTextField() {
            {
                setOpaque(false);
                setBackground(new java.awt.Color(245, 245, 245)); // Inner capsule color
                setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 50, 5, 15));

                setUI(new javax.swing.plaf.basic.BasicTextFieldUI() {
                    @Override
                    protected void paintBackground(java.awt.Graphics g) {
                        // We handle the background below
                    }
                });
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // 1. FILL THE ENTIRE SQUARE WITH WHITE
                // This matches your JPanel background and "hides" the corners
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRect(0, 0, getWidth(), getHeight());

                // 2. Draw the Grey Capsule on top of the white square
                g2.setColor(getBackground());
                g2.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);

                // 3. Draw the subtle border
                g2.setColor(new java.awt.Color(220, 220, 220));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);

                // 4. Draw the Icon at X=15
                try {
                    java.net.URL imgUrl = getClass().getResource("/carrentalsystem/ui/user/Icons/BasePrice.png");
                    if (imgUrl != null) {
                        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgUrl);
                        g2.drawImage(icon.getImage(), 15, (getHeight() - 20) / 2, 20, 20, null);
                    }
                } catch (Exception e) {}

                g2.dispose();
                super.paintComponent(g);
            }
        };
        lblModel = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField() {
            {
                setOpaque(false);
                setBackground(new java.awt.Color(245, 245, 245)); // Inner capsule color
                setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 50, 5, 15));

                setUI(new javax.swing.plaf.basic.BasicTextFieldUI() {
                    @Override
                    protected void paintBackground(java.awt.Graphics g) {
                        // We handle the background below
                    }
                });
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // 1. FILL THE ENTIRE SQUARE WITH WHITE
                // This matches your JPanel background and "hides" the corners
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRect(0, 0, getWidth(), getHeight());

                // 2. Draw the Grey Capsule on top of the white square
                g2.setColor(getBackground());
                g2.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);

                // 3. Draw the subtle border
                g2.setColor(new java.awt.Color(220, 220, 220));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);

                // 4. Draw the Icon at X=15
                try {
                    java.net.URL imgUrl = getClass().getResource("/carrentalsystem/ui/user/Icons/Car.png");
                    if (imgUrl != null) {
                        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgUrl);
                        g2.drawImage(icon.getImage(), 15, (getHeight() - 20) / 2, 20, 20, null);
                    }
                } catch (Exception e) {}

                g2.dispose();
                super.paintComponent(g);
            }
        };
        lblDescription = new javax.swing.JLabel();
        spDescription = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea() {
            {
                // 1. Basic Text Management
                setLineWrap(true);
                setWrapStyleWord(true);
                setOpaque(false);
                setBackground(new java.awt.Color(245, 245, 245));

                // 2. Padding (15px from all sides so text stays inside the curves)
                setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));

                // 3. Clear the default UI background painting
                setUI(new javax.swing.plaf.basic.BasicTextAreaUI() {
                    @Override
                    protected void paintBackground(java.awt.Graphics g) {
                        // Background is handled by paintComponent below
                    }
                });
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // 4. Fill the background with White to hide the "square" corners
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRect(0, 0, getWidth(), getHeight());

                // 5. Draw the Rounded Capsule
                g2.setColor(getBackground());
                g2.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);

                // 6. Draw the subtle border
                g2.setColor(new java.awt.Color(220, 220, 220));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);

                g2.dispose();
                super.paintComponent(g);
            }
        };
        lblCondition = new javax.swing.JLabel();
        cbCondition = new javax.swing.JComboBox<String>() {
            {
                setOpaque(false);
                setBackground(new java.awt.Color(245, 245, 245));

                // 1. Completely override the UI to remove the vertical line and blue border
                setUI(new javax.swing.plaf.basic.BasicComboBoxUI() {
                    @Override
                    protected javax.swing.JButton createArrowButton() {
                        // Create a button that is invisible (no border/content)
                        javax.swing.JButton button = new javax.swing.JButton();
                        button.setBorderPainted(false);
                        button.setContentAreaFilled(false);
                        button.setFocusPainted(false);
                        return button;
                    }
                });

                // 2. Padding (Left: 15px so text doesn't touch the curve)
                setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 10));
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // 3. Blend with your white card background
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRect(0, 0, getWidth(), getHeight());

                // 4. Draw the smooth capsule
                g2.setColor(getBackground());
                g2.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);

                g2.setColor(new java.awt.Color(220, 220, 220));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);

                // 5. Draw a simple Down Arrow manually (since we hid the button)
                int[] xPoints = {getWidth() - 25, getWidth() - 20, getWidth() - 15};
                int[] yPoints = {(getHeight() / 2) - 2, (getHeight() / 2) + 3, (getHeight() / 2) - 2};
                g2.setColor(new java.awt.Color(100, 100, 100)); // Dark grey arrow
                g2.fillPolygon(xPoints, yPoints, 3);

                g2.dispose();
                super.paintComponent(g);
            }
        };
        lblTransmission = new javax.swing.JLabel();
        cbTransmission = new javax.swing.JComboBox<String>() {
            {
                setOpaque(false);
                setBackground(new java.awt.Color(245, 245, 245));

                // 1. Completely override the UI to remove the vertical line and blue border
                setUI(new javax.swing.plaf.basic.BasicComboBoxUI() {
                    @Override
                    protected javax.swing.JButton createArrowButton() {
                        // Create a button that is invisible (no border/content)
                        javax.swing.JButton button = new javax.swing.JButton();
                        button.setBorderPainted(false);
                        button.setContentAreaFilled(false);
                        button.setFocusPainted(false);
                        return button;
                    }
                });

                // 2. Padding (Left: 15px so text doesn't touch the curve)
                setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 10));
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // 3. Blend with your white card background
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRect(0, 0, getWidth(), getHeight());

                // 4. Draw the smooth capsule
                g2.setColor(getBackground());
                g2.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);

                g2.setColor(new java.awt.Color(220, 220, 220));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);

                // 5. Draw a simple Down Arrow manually (since we hid the button)
                int[] xPoints = {getWidth() - 25, getWidth() - 20, getWidth() - 15};
                int[] yPoints = {(getHeight() / 2) - 2, (getHeight() / 2) + 3, (getHeight() / 2) - 2};
                g2.setColor(new java.awt.Color(100, 100, 100)); // Dark grey arrow
                g2.fillPolygon(xPoints, yPoints, 3);

                g2.dispose();
                super.paintComponent(g);
            }
        };
        lblVehicleType = new javax.swing.JLabel();
        cbVehicleType = new javax.swing.JComboBox<String>() {
            {
                setOpaque(false);
                setBackground(new java.awt.Color(245, 245, 245));

                // 1. Completely override the UI to remove the vertical line and blue border
                setUI(new javax.swing.plaf.basic.BasicComboBoxUI() {
                    @Override
                    protected javax.swing.JButton createArrowButton() {
                        // Create a button that is invisible (no border/content)
                        javax.swing.JButton button = new javax.swing.JButton();
                        button.setBorderPainted(false);
                        button.setContentAreaFilled(false);
                        button.setFocusPainted(false);
                        return button;
                    }
                });

                // 2. Padding (Left: 15px so text doesn't touch the curve)
                setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 10));
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // 3. Blend with your white card background
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRect(0, 0, getWidth(), getHeight());

                // 4. Draw the smooth capsule
                g2.setColor(getBackground());
                g2.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);

                g2.setColor(new java.awt.Color(220, 220, 220));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);

                // 5. Draw a simple Down Arrow manually (since we hid the button)
                int[] xPoints = {getWidth() - 25, getWidth() - 20, getWidth() - 15};
                int[] yPoints = {(getHeight() / 2) - 2, (getHeight() / 2) + 3, (getHeight() / 2) - 2};
                g2.setColor(new java.awt.Color(100, 100, 100)); // Dark grey arrow
                g2.fillPolygon(xPoints, yPoints, 3);

                g2.dispose();
                super.paintComponent(g);
            }
        };
        lblFuelType = new javax.swing.JLabel();
        cbFuelType = new javax.swing.JComboBox<String>() {
            {
                setOpaque(false);
                setBackground(new java.awt.Color(245, 245, 245));

                // 1. Completely override the UI to remove the vertical line and blue border
                setUI(new javax.swing.plaf.basic.BasicComboBoxUI() {
                    @Override
                    protected javax.swing.JButton createArrowButton() {
                        // Create a button that is invisible (no border/content)
                        javax.swing.JButton button = new javax.swing.JButton();
                        button.setBorderPainted(false);
                        button.setContentAreaFilled(false);
                        button.setFocusPainted(false);
                        return button;
                    }
                });

                // 2. Padding (Left: 15px so text doesn't touch the curve)
                setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 10));
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // 3. Blend with your white card background
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRect(0, 0, getWidth(), getHeight());

                // 4. Draw the smooth capsule
                g2.setColor(getBackground());
                g2.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);

                g2.setColor(new java.awt.Color(220, 220, 220));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);

                // 5. Draw a simple Down Arrow manually (since we hid the button)
                int[] xPoints = {getWidth() - 25, getWidth() - 20, getWidth() - 15};
                int[] yPoints = {(getHeight() / 2) - 2, (getHeight() / 2) + 3, (getHeight() / 2) - 2};
                g2.setColor(new java.awt.Color(100, 100, 100)); // Dark grey arrow
                g2.fillPolygon(xPoints, yPoints, 3);

                g2.dispose();
                super.paintComponent(g);
            }
        };
        lblSeats = new javax.swing.JLabel();
        cbSeats = new javax.swing.JComboBox<String>() {
            {
                setOpaque(false);
                setBackground(new java.awt.Color(245, 245, 245));

                // 1. Completely override the UI to remove the vertical line and blue border
                setUI(new javax.swing.plaf.basic.BasicComboBoxUI() {
                    @Override
                    protected javax.swing.JButton createArrowButton() {
                        // Create a button that is invisible (no border/content)
                        javax.swing.JButton button = new javax.swing.JButton();
                        button.setBorderPainted(false);
                        button.setContentAreaFilled(false);
                        button.setFocusPainted(false);
                        return button;
                    }
                });

                // 2. Padding (Left: 15px so text doesn't touch the curve)
                setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 10));
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // 3. Blend with your white card background
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRect(0, 0, getWidth(), getHeight());

                // 4. Draw the smooth capsule
                g2.setColor(getBackground());
                g2.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);

                g2.setColor(new java.awt.Color(220, 220, 220));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);

                // 5. Draw a simple Down Arrow manually (since we hid the button)
                int[] xPoints = {getWidth() - 25, getWidth() - 20, getWidth() - 15};
                int[] yPoints = {(getHeight() / 2) - 2, (getHeight() / 2) + 3, (getHeight() / 2) - 2};
                g2.setColor(new java.awt.Color(100, 100, 100)); // Dark grey arrow
                g2.fillPolygon(xPoints, yPoints, 3);

                g2.dispose();
                super.paintComponent(g);
            }
        };
        btnCreateListing = new javax.swing.JButton() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // Change color slightly when hovering/clicking for a modern feel
                if (getModel().isPressed()) {
                    g2.setColor(new java.awt.Color(50, 50, 50)); // Dark grey when clicked
                } else if (getModel().isRollover()) {
                    g2.setColor(new java.awt.Color(30, 30, 30)); // Slightly lighter black on hover
                } else {
                    g2.setColor(getBackground()); // Default Black
                }

                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30);
                g2.dispose();

                super.paintComponent(g);
            }

            @Override
            public void setBorder(javax.swing.border.Border border) {
                // Prevents square border from appearing
            }
        }
        ;

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setText("Add New Listing");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        pnlImageUpload.setBackground(new java.awt.Color(204, 204, 204));
        pnlImageUpload.setPreferredSize(new java.awt.Dimension(450, 250));
        pnlImageUpload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlImageUploadMouseClicked(evt);
            }
        });
        pnlImageUpload.setLayout(new java.awt.GridBagLayout());

        lblImageIcon.setForeground(new java.awt.Color(255, 255, 255));
        lblImageIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImageIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrentalsystem/ui/user/Camera.png"))); // NOI18N
        lblImageIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblImageIcon.setIconTextGap(0);
        lblImageIcon.setPreferredSize(new java.awt.Dimension(64, 64));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlImageUpload.add(lblImageIcon, gridBagConstraints);

        lblUploadText.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblUploadText.setForeground(new java.awt.Color(255, 255, 255));
        lblUploadText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUploadText.setText("Click to Upload Car Image");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 87, 41);
        pnlImageUpload.add(lblUploadText, gridBagConstraints);

        lblPhotoPreview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhotoPreview.setPreferredSize(new java.awt.Dimension(450, 250));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        pnlImageUpload.add(lblPhotoPreview, gridBagConstraints);

        add(pnlImageUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 360, 250));

        lblGenInfo.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblGenInfo.setText("General Information");
        add(lblGenInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        lblBrand.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblBrand.setText("Brand");
        add(lblBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        txtBrand.setBackground(new java.awt.Color(245, 245, 245));
        txtBrand.setColumns(35);
        txtBrand.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        txtBrand.setForeground(new java.awt.Color(180, 180, 180));
        txtBrand.setText("e.g., Toyota");
        txtBrand.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 45, 5, 5));
        txtBrand.setMargin(new java.awt.Insets(5, 35, 5, 10));
        txtBrand.setMinimumSize(new java.awt.Dimension(400, 45));
        txtBrand.setOpaque(true);
        txtBrand.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBrandFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBrandFocusLost(evt);
            }
        });
        txtBrand.addActionListener(this::txtBrandActionPerformed);
        add(txtBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 300, 45));

        lblBasePrice.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblBasePrice.setText("Base Price (PHP)");
        add(lblBasePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        txtBasePrice.setBackground(new java.awt.Color(245, 245, 245));
        txtBasePrice.setColumns(35);
        txtBasePrice.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        txtBasePrice.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 45, 5, 5));
        txtBasePrice.setMargin(new java.awt.Insets(5, 35, 5, 10));
        txtBasePrice.setMinimumSize(new java.awt.Dimension(400, 45));
        txtBasePrice.setOpaque(true);
        txtBasePrice.addActionListener(this::txtBasePriceActionPerformed);
        add(txtBasePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 300, 45));

        lblModel.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblModel.setText("Model");
        add(lblModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, -1, -1));

        txtModel.setBackground(new java.awt.Color(245, 245, 245));
        txtModel.setColumns(35);
        txtModel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        txtModel.setForeground(new java.awt.Color(180, 180, 180));
        txtModel.setText("e.g., Vios");
        txtModel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 45, 5, 5));
        txtModel.setMargin(new java.awt.Insets(5, 35, 5, 10));
        txtModel.setMinimumSize(new java.awt.Dimension(400, 45));
        txtModel.setOpaque(true);
        txtModel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtModelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtModelFocusLost(evt);
            }
        });
        txtModel.addActionListener(this::txtModelActionPerformed);
        add(txtModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, 320, 45));

        lblDescription.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblDescription.setText("Description");
        add(lblDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        spDescription.setOpaque(false);

        txtDescription.setBackground(new java.awt.Color(245, 245, 245));
        txtDescription.setColumns(20);
        txtDescription.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        txtDescription.setForeground(new java.awt.Color(180, 180, 180));
        txtDescription.setRows(5);
        txtDescription.setText("Tell renters what makes your car special.");
        txtDescription.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15));
        txtDescription.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDescriptionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescriptionFocusLost(evt);
            }
        });
        spDescription.setViewportView(txtDescription);

        add(spDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 360, 150));

        lblCondition.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblCondition.setText("Condition");
        add(lblCondition, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, -1, -1));

        cbCondition.setBackground(new java.awt.Color(245, 245, 245));
        cbCondition.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        cbCondition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Excellent", "Good", "Fair" }));
        cbCondition.addActionListener(this::cbConditionActionPerformed);
        add(cbCondition, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 320, 45));

        lblTransmission.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblTransmission.setText("Transmission");
        add(lblTransmission, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, -1, -1));

        cbTransmission.setBackground(new java.awt.Color(245, 245, 245));
        cbTransmission.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        cbTransmission.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manual", "Automatic", " " }));
        add(cbTransmission, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 300, 45));

        lblVehicleType.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblVehicleType.setText("Vehicle Type");
        add(lblVehicleType, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, -1, -1));

        cbVehicleType.setBackground(new java.awt.Color(245, 245, 245));
        cbVehicleType.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        cbVehicleType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedan", "SUV", "Hatchback", "Van", "Pickup", "Off-road", "Sports", "Convertible", "Crossover", "Wagon", "Muscle", "Roadster", "Cabriolet", "Limousine" }));
        add(cbVehicleType, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, 320, 45));

        lblFuelType.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblFuelType.setText("Fuel Type");
        add(lblFuelType, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, -1, -1));

        cbFuelType.setBackground(new java.awt.Color(245, 245, 245));
        cbFuelType.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        cbFuelType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gasoline", "Diesel", "Electric", "Hybrid" }));
        add(cbFuelType, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 300, 45));

        lblSeats.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblSeats.setText("Seats");
        add(lblSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, -1, -1));

        cbSeats.setBackground(new java.awt.Color(245, 245, 245));
        cbSeats.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        cbSeats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "4", "5", "7", "8", "12", "16" }));
        add(cbSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 490, 320, 45));

        btnCreateListing.setBackground(new java.awt.Color(156, 142, 128));
        btnCreateListing.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        btnCreateListing.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateListing.setText("Create Listing");
        btnCreateListing.setContentAreaFilled(false);
        btnCreateListing.setPreferredSize(new java.awt.Dimension(200, 50));
        btnCreateListing.addActionListener(this::btnCreateListingActionPerformed);
        add(btnCreateListing, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 580, 400, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void pnlImageUploadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlImageUploadMouseClicked
        // TODO add your handling code here:
    javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    javax.swing.filechooser.FileNameExtensionFilter filter
        = new javax.swing.filechooser.FileNameExtensionFilter("Images", "jpg", "png", "jpeg");
    fileChooser.setFileFilter(filter);
    
    int result = fileChooser.showOpenDialog(this);
    
    if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
        java.io.File selectedFile = fileChooser.getSelectedFile();
        
        // 1. Save path to a class variable
        this.selectedImagePath = carrentalsystem.utils.ImageUtil.copyImage(selectedFile);
        
        if (selectedImagePath != null) {
            // 2. HIDE the instructions
            lblImageIcon.setVisible(false);
            lblUploadText.setVisible(false);
            
            // 3. SHOW and update the preview label
            lblPhotoPreview.setVisible(true);
            carrentalsystem.utils.ImageUtil.applyScaledImage(lblPhotoPreview, selectedImagePath, 450, 250);
            
            // 4. Refresh to ensure the new image paints
            pnlImageUpload.revalidate();
            pnlImageUpload.repaint();
        }
    }
    }//GEN-LAST:event_pnlImageUploadMouseClicked

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandActionPerformed

    private void txtBrandFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBrandFocusGained
        // TODO add your handling code here:
        if (txtBrand.getText().equals("e.g., Toyota")) {
            txtBrand.setText("");
            txtBrand.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_txtBrandFocusGained

    private void txtBrandFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBrandFocusLost
        // TODO add your handling code here:
        if (txtBrand.getText().isEmpty()) {
            txtBrand.setText("e.g., Toyota");
            txtBrand.setForeground(new java.awt.Color(180, 180, 180)); // Grey placeholder
        }
    }//GEN-LAST:event_txtBrandFocusLost

    private void txtBasePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBasePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBasePriceActionPerformed

    private void txtModelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtModelFocusGained
        // TODO add your handling code here:
        if (txtModel.getText().equals("e.g., Vios")) {
            txtModel.setText("");
            txtModel.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_txtModelFocusGained

    private void txtModelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtModelFocusLost
        // TODO add your handling code here:
        if (txtModel.getText().isEmpty()) {
            txtModel.setText("e.g., Vios");
            txtModel.setForeground(new java.awt.Color(180, 180, 180));
        }
    }//GEN-LAST:event_txtModelFocusLost

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed

    private void btnCreateListingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateListingActionPerformed
        // TODO add your handling code here:
        carrentalsystem.models.User user = carrentalsystem.core.SessionManager.getCurrentUser();

        // Safety check for NEW listings only (currentEditingCarId == -1)
        if (currentEditingCarId == -1 && "FREE".equalsIgnoreCase(user.getTier())) {
            try {
                int count = new carrentalsystem.services.CarService().countUserListings(user.getUserId());
                if (count >= 5) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Limit reached! Free accounts are restricted to 5 listings.");
                    return;
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
        //Debug
        System.out.println("[DEBUG] Create Button Clicked");
        
        // Basic UI Validation
        String brand = txtBrand.getText().trim();
        String model = txtModel.getText().trim();
        String priceStr = txtBasePrice.getText().trim();
        String description = txtDescription.getText().trim();
        
        //Debug
        System.out.println("[DEBUG] Inputs - Brand: " + brand + ", Model: " + model + ", Price: " + priceStr);
        
        if (brand.isEmpty() || brand.equals("e.g., Toyota") || model.isEmpty() || selectedImagePath == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields and upload a car photo.");
            return;
        }

        try {
            // 2. Create the Car object to match the Service's mapCar structure
            carrentalsystem.models.Car newCar = new carrentalsystem.models.Car();

            // Populate fields based on your ComboBoxes and TextFields
            newCar.setOwnerId(carrentalsystem.core.SessionManager.getCurrentUser().getUserId());
            newCar.setBrand(brand);
            newCar.setModel(model);
            newCar.setBasePrice(Double.parseDouble(priceStr));
            newCar.setDescription(description);
            newCar.setImagePath(selectedImagePath); // Stored path from ImageUtil.copyImage

            // These match the new columns we added to the DB and mapCar
            newCar.setSeats(Integer.parseInt(cbSeats.getSelectedItem().toString()));
            newCar.setType(cbVehicleType.getSelectedItem().toString());
            newCar.setTransmission(cbTransmission.getSelectedItem().toString());
            newCar.setFuelType(cbFuelType.getSelectedItem().toString());
            newCar.setCondition(cbCondition.getSelectedItem().toString());

            // Set defaults for the remaining fields
            newCar.setStatus("PENDING_APPROVAL");
            newCar.setPriority(false);

            // 3. Call the Service to save to Database
            carrentalsystem.interfaces.ICarService carService = new carrentalsystem.services.CarService();
            
            if(currentEditingCarId == -1){
            int generatedId = carService.addCar(newCar);
            System.out.println("[DEBUG] AddCar Result ID: " + generatedId);
            
            if (generatedId != -1) {
                //Debug
                System.out.println("[DEBUG] Database Save Successful. ID: " + generatedId);
                
                newCar.setCarId(generatedId);
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Listing created successfully!\nPending for approval from the admin.",
                        "Success",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            } else {
                newCar.setCarId(currentEditingCarId);
                carService.updateCar(newCar);
                
                javax.swing.JOptionPane.showMessageDialog(this, "Listing updated successfully!");
                
            }
            
            // 4. Update the Dashboard Feed immediately
            if (dashboard != null) {
                //Debug
                System.out.println("[DEBUG] Calling Dashboard Refresh...");
                dashboard.refreshCarFeed();
                dashboard.showCarDetails(newCar);
            } else {
                System.out.println("[DEBUG] ERROR: Dashboard reference is NULL!");
            }
            
            currentEditingCarId = -1;
            btnCreateListing.setText("Create Listing");
            clearForm();

        } catch (Exception e) {
            //Debug
            System.out.println("[DEBUG] Exception: " + e.getMessage());
            e.printStackTrace();
            //javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid numeric price.");
        } 
    }//GEN-LAST:event_btnCreateListingActionPerformed

    private void cbConditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbConditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbConditionActionPerformed

    private void txtDescriptionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescriptionFocusGained
        // TODO add your handling code here:
        if (txtDescription.getText().equals("Tell renters what makes your car special.")) {
            txtDescription.setText("");
            txtDescription.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_txtDescriptionFocusGained

    private void txtDescriptionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescriptionFocusLost
        // TODO add your handling code here:
        if (txtDescription.getText().trim().isEmpty()) {
            txtDescription.setText("Tell renters what makes your car special.");
            txtDescription.setForeground(new java.awt.Color(180, 180, 180)); // Light grey
        }
    }//GEN-LAST:event_txtDescriptionFocusLost
    
    public void setDashboard(MainDashboard dashboard) {
        this.dashboard = dashboard;
    }
    
    @Override
    protected void paintComponent(java.awt.Graphics g) {
        java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
        g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

        // Paint the white rounded background
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30);

        g2.dispose();
        super.paintComponent(g);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateListing;
    private javax.swing.JComboBox<String> cbCondition;
    private javax.swing.JComboBox<String> cbFuelType;
    private javax.swing.JComboBox<String> cbSeats;
    private javax.swing.JComboBox<String> cbTransmission;
    private javax.swing.JComboBox<String> cbVehicleType;
    private javax.swing.JLabel lblBasePrice;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblCondition;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblFuelType;
    private javax.swing.JLabel lblGenInfo;
    private javax.swing.JLabel lblImageIcon;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblPhotoPreview;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTransmission;
    private javax.swing.JLabel lblUploadText;
    private javax.swing.JLabel lblVehicleType;
    private javax.swing.JPanel pnlImageUpload;
    private javax.swing.JScrollPane spDescription;
    private javax.swing.JTextField txtBasePrice;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtModel;
    // End of variables declaration//GEN-END:variables
}
