/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package carrentalsystem.ui.user;

import carrentalsystem.utils.RoundedBorder;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author macbookairm1grey
 */
public class AddListPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddListPanel
     */
    private MainDashboard dashboard;
    private String selectedImagePath = null;
    private Object txtPrice;
    private int currentEditingCarId;

    public AddListPanel() {
        initComponents();

        // 1. Set the look of the card
        this.setBackground(java.awt.Color.WHITE);
        this.setOpaque(false); // Allows the MainDashboard nude background to show through corners

        // 2. Apply the Rounded Border (30px radius, subtle grey border)
        // Ensure you have created RoundedBorder.java in carrentalsystem.utils
        this.setBorder(new carrentalsystem.utils.RoundedBorder(30, new java.awt.Color(220, 220, 220), 1));

        // Ensure preview is hidden initially
        lblPhotoPreview.setVisible(false);

        // This removes the border from the scroll pane itself
        spDescription.setBorder(null);
        spDescription.setOpaque(false);
        spDescription.getViewport().setOpaque(false);
    }

    private void clearForm() {
        txtBrand.setText("e.g., Toyota");
        txtModel.setText("e.g., Vios");
        txtBasePrice.setText("");
        txtDescription.setText("Tell renters what makes your car special.");
        lblPhotoPreview.setIcon(null);
        lblPhotoPreview.setVisible(false);
        lblImageIcon.setVisible(true);
        lblUploadText.setVisible(true);
        selectedImagePath = null;
        txtBrand.setText("");
        txtModel.setText("");
        txtBasePrice.setText("");
        txtDescription.setText("");
        txtPlateNumber.setText("");
        txtColor.setText("");
        txtMileage.setText("");
        cbDriverOption.setSelectedIndex(0);
    }

    // Inside your AddList panel class (e.g., AddListPanel.java)
    public void prepareEdit(carrentalsystem.models.Car car) {
        // Fill text fields with existing car data
        txtBrand.setText(car.getBrand());
        txtModel.setText(car.getModel());
        txtBasePrice.setText(String.valueOf(car.getBasePrice()));

        // Store the Car ID in a hidden variable to know this is an UPDATE, not a NEW car
        this.currentEditingCarId = car.getCarId();

        // Show the current image
        carrentalsystem.utils.ImageUtil.applyScaledImage(lblPhotoPreview, car.getImagePath(), 300, 200);

        // Change the button text from "Add Car" to "Update Listing"
        btnCreateListing.setText("Update Listing");
    }

    public void prepareAdd() {
        this.currentEditingCarId = -1; // CRITICAL: Reset the state[cite: 10]
        clearForm();                   // Wipe the text fields
        btnCreateListing.setText("Create Listing"); // Fix the button label[cite: 10]
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblTitle = new javax.swing.JLabel();
        pnlImageUpload = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(getBackground());
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 20, 20);
                float[] dash = {10.0f, 5.0f};
                g2.setStroke(new java.awt.BasicStroke(2, java.awt.BasicStroke.CAP_BUTT, java.awt.BasicStroke.JOIN_MITER, 10.0f, dash, 0.0f));
                g2.setColor(new java.awt.Color(200, 200, 200));
                g2.drawRoundRect(1, 1, getWidth() - 2, getHeight() - 2, 20, 20);
                g2.dispose();
            }
        };
        lblImageIcon = new javax.swing.JLabel();
        lblUploadText = new javax.swing.JLabel();
        lblPhotoPreview = new javax.swing.JLabel();
        lblGenInfo = new javax.swing.JLabel();
        lblBrand = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField() {
            {
                setOpaque(false);
                setBackground(new java.awt.Color(245, 245, 245)); // Inner capsule color
                setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 50, 5, 15));

                setUI(new javax.swing.plaf.basic.BasicTextFieldUI() {
                    @Override
                    protected void paintBackground(java.awt.Graphics g) {
                        // We handle the background below
                    }
                });
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // 1. FILL THE ENTIRE SQUARE WITH WHITE
                // This matches your JPanel background and "hides" the corners
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRect(0, 0, getWidth(), getHeight());

                // 2. Draw the Grey Capsule on top of the white square
                g2.setColor(getBackground());
                g2.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);

                // 3. Draw the subtle border
                g2.setColor(new java.awt.Color(220, 220, 220));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);

                // 4. Draw the Icon at X=15
                try {
                    java.net.URL imgUrl = getClass().getResource("/carrentalsystem/ui/user/Icons/Car.png");
                    if (imgUrl != null) {
                        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgUrl);
                        g2.drawImage(icon.getImage(), 15, (getHeight() - 20) / 2, 20, 20, null);
                    }
                } catch (Exception e) {}

                g2.dispose();
                super.paintComponent(g);
            }
        };
        lblBasePrice = new javax.swing.JLabel();
        txtBasePrice = new javax.swing.JTextField() {
            {
                setOpaque(false);
                setBackground(new java.awt.Color(245, 245, 245)); // Inner capsule color
                setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 50, 5, 15));

                setUI(new javax.swing.plaf.basic.BasicTextFieldUI() {
                    @Override
                    protected void paintBackground(java.awt.Graphics g) {
                        // We handle the background below
                    }
                });
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // 1. FILL THE ENTIRE SQUARE WITH WHITE
                // This matches your JPanel background and "hides" the corners
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRect(0, 0, getWidth(), getHeight());

                // 2. Draw the Grey Capsule on top of the white square
                g2.setColor(getBackground());
                g2.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);

                // 3. Draw the subtle border
                g2.setColor(new java.awt.Color(220, 220, 220));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);

                // 4. Draw the Icon at X=15
                try {
                    java.net.URL imgUrl = getClass().getResource("/carrentalsystem/ui/user/Icons/BasePrice.png");
                    if (imgUrl != null) {
                        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgUrl);
                        g2.drawImage(icon.getImage(), 15, (getHeight() - 20) / 2, 20, 20, null);
                    }
                } catch (Exception e) {}

                g2.dispose();
                super.paintComponent(g);
            }
        };
        lblModel = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField() {
            {
                setOpaque(false);
                setBackground(new java.awt.Color(245, 245, 245)); // Inner capsule color
                setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 50, 5, 15));

                setUI(new javax.swing.plaf.basic.BasicTextFieldUI() {
                    @Override
                    protected void paintBackground(java.awt.Graphics g) {
                        // We handle the background below
                    }
                });
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // 1. FILL THE ENTIRE SQUARE WITH WHITE
                // This matches your JPanel background and "hides" the corners
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRect(0, 0, getWidth(), getHeight());

                // 2. Draw the Grey Capsule on top of the white square
                g2.setColor(getBackground());
                g2.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);

                // 3. Draw the subtle border
                g2.setColor(new java.awt.Color(220, 220, 220));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);

                // 4. Draw the Icon at X=15
                try {
                    java.net.URL imgUrl = getClass().getResource("/carrentalsystem/ui/user/Icons/Car.png");
                    if (imgUrl != null) {
                        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgUrl);
                        g2.drawImage(icon.getImage(), 15, (getHeight() - 20) / 2, 20, 20, null);
                    }
                } catch (Exception e) {}

                g2.dispose();
                super.paintComponent(g);
            }
        };
        lblDescription = new javax.swing.JLabel();
        spDescription = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea() {
            {
                // 1. Basic Text Management
                setLineWrap(true);
                setWrapStyleWord(true);
                setOpaque(false);
                setBackground(new java.awt.Color(245, 245, 245));

                // 2. Padding (15px from all sides so text stays inside the curves)
                setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));

                // 3. Clear the default UI background painting
                setUI(new javax.swing.plaf.basic.BasicTextAreaUI() {
                    @Override
                    protected void paintBackground(java.awt.Graphics g) {
                        // Background is handled by paintComponent below
                    }
                });
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // 4. Fill the background with White to hide the "square" corners
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRect(0, 0, getWidth(), getHeight());

                // 5. Draw the Rounded Capsule
                g2.setColor(getBackground());
                g2.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);

                // 6. Draw the subtle border
                g2.setColor(new java.awt.Color(220, 220, 220));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);

                g2.dispose();
                super.paintComponent(g);
            }
        };
        lblCondition = new javax.swing.JLabel();
        cbCondition = new javax.swing.JComboBox<String>() {
            {
                setOpaque(false);
                setBackground(new java.awt.Color(245, 245, 245));

                // 1. Completely override the UI to remove the vertical line and blue border
                setUI(new javax.swing.plaf.basic.BasicComboBoxUI() {
                    @Override
                    protected javax.swing.JButton createArrowButton() {
                        // Create a button that is invisible (no border/content)
                        javax.swing.JButton button = new javax.swing.JButton();
                        button.setBorderPainted(false);
                        button.setContentAreaFilled(false);
                        button.setFocusPainted(false);
                        return button;
                    }
                });

                // 2. Padding (Left: 15px so text doesn't touch the curve)
                setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 10));
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // 3. Blend with your white card background
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRect(0, 0, getWidth(), getHeight());

                // 4. Draw the smooth capsule
                g2.setColor(getBackground());
                g2.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);

                g2.setColor(new java.awt.Color(220, 220, 220));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);

                // 5. Draw a simple Down Arrow manually (since we hid the button)
                int[] xPoints = {getWidth() - 25, getWidth() - 20, getWidth() - 15};
                int[] yPoints = {(getHeight() / 2) - 2, (getHeight() / 2) + 3, (getHeight() / 2) - 2};
                g2.setColor(new java.awt.Color(100, 100, 100)); // Dark grey arrow
                g2.fillPolygon(xPoints, yPoints, 3);

                g2.dispose();
                super.paintComponent(g);
            }
        };
        lblTransmission = new javax.swing.JLabel();
        cbTransmission = new javax.swing.JComboBox<String>() {
            {
                setOpaque(false);
                setBackground(new java.awt.Color(245, 245, 245));

                // 1. Completely override the UI to remove the vertical line and blue border
                setUI(new javax.swing.plaf.basic.BasicComboBoxUI() {
                    @Override
                    protected javax.swing.JButton createArrowButton() {
                        // Create a button that is invisible (no border/content)
                        javax.swing.JButton button = new javax.swing.JButton();
                        button.setBorderPainted(false);
                        button.setContentAreaFilled(false);
                        button.setFocusPainted(false);
                        return button;
                    }
                });

                // 2. Padding (Left: 15px so text doesn't touch the curve)
                setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 10));
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // 3. Blend with your white card background
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRect(0, 0, getWidth(), getHeight());

                // 4. Draw the smooth capsule
                g2.setColor(getBackground());
                g2.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);

                g2.setColor(new java.awt.Color(220, 220, 220));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);

                // 5. Draw a simple Down Arrow manually (since we hid the button)
                int[] xPoints = {getWidth() - 25, getWidth() - 20, getWidth() - 15};
                int[] yPoints = {(getHeight() / 2) - 2, (getHeight() / 2) + 3, (getHeight() / 2) - 2};
                g2.setColor(new java.awt.Color(100, 100, 100)); // Dark grey arrow
                g2.fillPolygon(xPoints, yPoints, 3);

                g2.dispose();
                super.paintComponent(g);
            }
        };
        lblVehicleType = new javax.swing.JLabel();
        cbVehicleType1 = new javax.swing.JComboBox<String>() {
            {
                setOpaque(false);
                setBackground(new java.awt.Color(245, 245, 245));

                // 1. Completely override the UI to remove the vertical line and blue border
                setUI(new javax.swing.plaf.basic.BasicComboBoxUI() {
                    @Override
                    protected javax.swing.JButton createArrowButton() {
                        // Create a button that is invisible (no border/content)
                        javax.swing.JButton button = new javax.swing.JButton();
                        button.setBorderPainted(false);
                        button.setContentAreaFilled(false);
                        button.setFocusPainted(false);
                        return button;
                    }
                });

                // 2. Padding (Left: 15px so text doesn't touch the curve)
                setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 10));
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // 3. Blend with your white card background
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRect(0, 0, getWidth(), getHeight());

                // 4. Draw the smooth capsule
                g2.setColor(getBackground());
                g2.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);

                g2.setColor(new java.awt.Color(220, 220, 220));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);

                // 5. Draw a simple Down Arrow manually (since we hid the button)
                int[] xPoints = {getWidth() - 25, getWidth() - 20, getWidth() - 15};
                int[] yPoints = {(getHeight() / 2) - 2, (getHeight() / 2) + 3, (getHeight() / 2) - 2};
                g2.setColor(new java.awt.Color(100, 100, 100)); // Dark grey arrow
                g2.fillPolygon(xPoints, yPoints, 3);

                g2.dispose();
                super.paintComponent(g);
            }
        };
        lblFuelType = new javax.swing.JLabel();
        cbFuelType = new javax.swing.JComboBox<String>() {
            {
                setOpaque(false);
                setBackground(new java.awt.Color(245, 245, 245));

                // 1. Completely override the UI to remove the vertical line and blue border
                setUI(new javax.swing.plaf.basic.BasicComboBoxUI() {
                    @Override
                    protected javax.swing.JButton createArrowButton() {
                        // Create a button that is invisible (no border/content)
                        javax.swing.JButton button = new javax.swing.JButton();
                        button.setBorderPainted(false);
                        button.setContentAreaFilled(false);
                        button.setFocusPainted(false);
                        return button;
                    }
                });

                // 2. Padding (Left: 15px so text doesn't touch the curve)
                setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 10));
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // 3. Blend with your white card background
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRect(0, 0, getWidth(), getHeight());

                // 4. Draw the smooth capsule
                g2.setColor(getBackground());
                g2.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);

                g2.setColor(new java.awt.Color(220, 220, 220));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);

                // 5. Draw a simple Down Arrow manually (since we hid the button)
                int[] xPoints = {getWidth() - 25, getWidth() - 20, getWidth() - 15};
                int[] yPoints = {(getHeight() / 2) - 2, (getHeight() / 2) + 3, (getHeight() / 2) - 2};
                g2.setColor(new java.awt.Color(100, 100, 100)); // Dark grey arrow
                g2.fillPolygon(xPoints, yPoints, 3);

                g2.dispose();
                super.paintComponent(g);
            }
        };
        lblSeats = new javax.swing.JLabel();
        cbSeats = new javax.swing.JComboBox<String>() {
            {
                setOpaque(false);
                setBackground(new java.awt.Color(245, 245, 245));

                // 1. Completely override the UI to remove the vertical line and blue border
                setUI(new javax.swing.plaf.basic.BasicComboBoxUI() {
                    @Override
                    protected javax.swing.JButton createArrowButton() {
                        // Create a button that is invisible (no border/content)
                        javax.swing.JButton button = new javax.swing.JButton();
                        button.setBorderPainted(false);
                        button.setContentAreaFilled(false);
                        button.setFocusPainted(false);
                        return button;
                    }
                });

                // 2. Padding (Left: 15px so text doesn't touch the curve)
                setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 10));
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // 3. Blend with your white card background
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRect(0, 0, getWidth(), getHeight());

                // 4. Draw the smooth capsule
                g2.setColor(getBackground());
                g2.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);

                g2.setColor(new java.awt.Color(220, 220, 220));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);

                // 5. Draw a simple Down Arrow manually (since we hid the button)
                int[] xPoints = {getWidth() - 25, getWidth() - 20, getWidth() - 15};
                int[] yPoints = {(getHeight() / 2) - 2, (getHeight() / 2) + 3, (getHeight() / 2) - 2};
                g2.setColor(new java.awt.Color(100, 100, 100)); // Dark grey arrow
                g2.fillPolygon(xPoints, yPoints, 3);

                g2.dispose();
                super.paintComponent(g);
            }
        };
        btnCreateListing = new javax.swing.JButton() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // Change color slightly when hovering/clicking for a modern feel
                if (getModel().isPressed()) {
                    g2.setColor(new java.awt.Color(50, 50, 50)); // Dark grey when clicked
                } else if (getModel().isRollover()) {
                    g2.setColor(new java.awt.Color(30, 30, 30)); // Slightly lighter black on hover
                } else {
                    g2.setColor(getBackground()); // Default Black
                }

                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30);
                g2.dispose();

                super.paintComponent(g);
            }

            @Override
            public void setBorder(javax.swing.border.Border border) {
                // Prevents square border from appearing
            }
        }
        ;
        lblPlateNumber = new javax.swing.JLabel();
        txtPlateNumber = new javax.swing.JTextField() {
            {
                setOpaque(false);
                setBackground(new java.awt.Color(245, 245, 245)); // Inner capsule color
                setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 50, 5, 15));

                setUI(new javax.swing.plaf.basic.BasicTextFieldUI() {
                    @Override
                    protected void paintBackground(java.awt.Graphics g) {
                        // We handle the background below
                    }
                });
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // 1. FILL THE ENTIRE SQUARE WITH WHITE
                // This matches your JPanel background and "hides" the corners
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRect(0, 0, getWidth(), getHeight());

                // 2. Draw the Grey Capsule on top of the white square
                g2.setColor(getBackground());
                g2.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);

                // 3. Draw the subtle border
                g2.setColor(new java.awt.Color(220, 220, 220));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);

                // 4. Draw the Icon at X=15
                try {
                    java.net.URL imgUrl = getClass().getResource("/carrentalsystem/ui/user/Icons/BasePrice.png");
                    if (imgUrl != null) {
                        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgUrl);
                        g2.drawImage(icon.getImage(), 15, (getHeight() - 20) / 2, 20, 20, null);
                    }
                } catch (Exception e) {}

                g2.dispose();
                super.paintComponent(g);
            }
        };
        lblMileage = new javax.swing.JLabel();
        txtMileage = new javax.swing.JTextField() {
            {
                setOpaque(false);
                setBackground(new java.awt.Color(245, 245, 245)); // Inner capsule color
                setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 50, 5, 15));

                setUI(new javax.swing.plaf.basic.BasicTextFieldUI() {
                    @Override
                    protected void paintBackground(java.awt.Graphics g) {
                        // We handle the background below
                    }
                });
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // 1. FILL THE ENTIRE SQUARE WITH WHITE
                // This matches your JPanel background and "hides" the corners
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRect(0, 0, getWidth(), getHeight());

                // 2. Draw the Grey Capsule on top of the white square
                g2.setColor(getBackground());
                g2.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);

                // 3. Draw the subtle border
                g2.setColor(new java.awt.Color(220, 220, 220));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);

                // 4. Draw the Icon at X=15
                try {
                    java.net.URL imgUrl = getClass().getResource("/carrentalsystem/ui/user/Icons/BasePrice.png");
                    if (imgUrl != null) {
                        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgUrl);
                        g2.drawImage(icon.getImage(), 15, (getHeight() - 20) / 2, 20, 20, null);
                    }
                } catch (Exception e) {}

                g2.dispose();
                super.paintComponent(g);
            }
        };
        lblColor = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField() {
            {
                setOpaque(false);
                setBackground(new java.awt.Color(245, 245, 245)); // Inner capsule color
                setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 50, 5, 15));

                setUI(new javax.swing.plaf.basic.BasicTextFieldUI() {
                    @Override
                    protected void paintBackground(java.awt.Graphics g) {
                        // We handle the background below
                    }
                });
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // 1. FILL THE ENTIRE SQUARE WITH WHITE
                // This matches your JPanel background and "hides" the corners
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRect(0, 0, getWidth(), getHeight());

                // 2. Draw the Grey Capsule on top of the white square
                g2.setColor(getBackground());
                g2.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);

                // 3. Draw the subtle border
                g2.setColor(new java.awt.Color(220, 220, 220));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);

                // 4. Draw the Icon at X=15
                try {
                    java.net.URL imgUrl = getClass().getResource("/carrentalsystem/ui/user/Icons/BasePrice.png");
                    if (imgUrl != null) {
                        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgUrl);
                        g2.drawImage(icon.getImage(), 15, (getHeight() - 20) / 2, 20, 20, null);
                    }
                } catch (Exception e) {}

                g2.dispose();
                super.paintComponent(g);
            }
        };
        lblDriverOption = new javax.swing.JLabel();
        cbDriverOption = new javax.swing.JComboBox<String>() {
            {
                setOpaque(false);
                setBackground(new java.awt.Color(245, 245, 245));

                // 1. Completely override the UI to remove the vertical line and blue border
                setUI(new javax.swing.plaf.basic.BasicComboBoxUI() {
                    @Override
                    protected javax.swing.JButton createArrowButton() {
                        // Create a button that is invisible (no border/content)
                        javax.swing.JButton button = new javax.swing.JButton();
                        button.setBorderPainted(false);
                        button.setContentAreaFilled(false);
                        button.setFocusPainted(false);
                        return button;
                    }
                });

                // 2. Padding (Left: 15px so text doesn't touch the curve)
                setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 10));
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // 3. Blend with your white card background
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRect(0, 0, getWidth(), getHeight());

                // 4. Draw the smooth capsule
                g2.setColor(getBackground());
                g2.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);

                g2.setColor(new java.awt.Color(220, 220, 220));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);

                // 5. Draw a simple Down Arrow manually (since we hid the button)
                int[] xPoints = {getWidth() - 25, getWidth() - 20, getWidth() - 15};
                int[] yPoints = {(getHeight() / 2) - 2, (getHeight() / 2) + 3, (getHeight() / 2) - 2};
                g2.setColor(new java.awt.Color(100, 100, 100)); // Dark grey arrow
                g2.fillPolygon(xPoints, yPoints, 3);

                g2.dispose();
                super.paintComponent(g);
            }
        };

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setText("Add New Listing");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        pnlImageUpload.setBackground(new java.awt.Color(204, 204, 204));
        pnlImageUpload.setPreferredSize(new java.awt.Dimension(450, 250));
        pnlImageUpload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlImageUploadMouseClicked(evt);
            }
        });
        pnlImageUpload.setLayout(new java.awt.GridBagLayout());

        lblImageIcon.setForeground(new java.awt.Color(255, 255, 255));
        lblImageIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImageIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrentalsystem/ui/user/Camera.png"))); // NOI18N
        lblImageIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblImageIcon.setIconTextGap(0);
        lblImageIcon.setPreferredSize(new java.awt.Dimension(64, 64));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlImageUpload.add(lblImageIcon, gridBagConstraints);

        lblUploadText.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblUploadText.setForeground(new java.awt.Color(255, 255, 255));
        lblUploadText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUploadText.setText("Click to Upload Car Image");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 87, 41);
        pnlImageUpload.add(lblUploadText, gridBagConstraints);

        lblPhotoPreview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhotoPreview.setPreferredSize(new java.awt.Dimension(450, 250));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        pnlImageUpload.add(lblPhotoPreview, gridBagConstraints);

        add(pnlImageUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 350, 270));

        lblGenInfo.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblGenInfo.setText("General Information");
        add(lblGenInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        lblBrand.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblBrand.setText("Brand");
        add(lblBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        txtBrand.setBackground(new java.awt.Color(245, 245, 245));
        txtBrand.setColumns(35);
        txtBrand.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        txtBrand.setForeground(new java.awt.Color(180, 180, 180));
        txtBrand.setText("e.g., Toyota");
        txtBrand.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 45, 5, 5));
        txtBrand.setMargin(new java.awt.Insets(5, 35, 5, 10));
        txtBrand.setMinimumSize(new java.awt.Dimension(400, 45));
        txtBrand.setOpaque(true);
        txtBrand.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBrandFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBrandFocusLost(evt);
            }
        });
        txtBrand.addActionListener(this::txtBrandActionPerformed);
        add(txtBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 290, 40));

        lblBasePrice.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblBasePrice.setText("Base Price (PHP)");
        add(lblBasePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        txtBasePrice.setBackground(new java.awt.Color(245, 245, 245));
        txtBasePrice.setColumns(35);
        txtBasePrice.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        txtBasePrice.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 45, 5, 5));
        txtBasePrice.setMargin(new java.awt.Insets(5, 35, 5, 10));
        txtBasePrice.setMinimumSize(new java.awt.Dimension(400, 45));
        txtBasePrice.setOpaque(true);
        txtBasePrice.addActionListener(this::txtBasePriceActionPerformed);
        add(txtBasePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 290, 40));

        lblModel.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblModel.setText("Model");
        add(lblModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, -1, -1));

        txtModel.setBackground(new java.awt.Color(245, 245, 245));
        txtModel.setColumns(35);
        txtModel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        txtModel.setForeground(new java.awt.Color(180, 180, 180));
        txtModel.setText("e.g., Vios");
        txtModel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 45, 5, 5));
        txtModel.setMargin(new java.awt.Insets(5, 35, 5, 10));
        txtModel.setMinimumSize(new java.awt.Dimension(400, 45));
        txtModel.setOpaque(true);
        txtModel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtModelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtModelFocusLost(evt);
            }
        });
        txtModel.addActionListener(this::txtModelActionPerformed);
        add(txtModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 310, 40));

        lblDescription.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblDescription.setText("Description");
        add(lblDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, 40));

        spDescription.setOpaque(false);

        txtDescription.setBackground(new java.awt.Color(245, 245, 245));
        txtDescription.setColumns(20);
        txtDescription.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        txtDescription.setForeground(new java.awt.Color(180, 180, 180));
        txtDescription.setRows(5);
        txtDescription.setText("Tell renters what makes your car special.");
        txtDescription.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15));
        txtDescription.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDescriptionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescriptionFocusLost(evt);
            }
        });
        spDescription.setViewportView(txtDescription);

        add(spDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 350, 220));

        lblCondition.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblCondition.setText("Condition");
        add(lblCondition, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, -1, -1));

        cbCondition.setBackground(new java.awt.Color(245, 245, 245));
        cbCondition.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        cbCondition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Excellent", "Good", "Fair" }));
        cbCondition.addActionListener(this::cbConditionActionPerformed);
        add(cbCondition, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 310, 40));

        lblTransmission.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblTransmission.setText("Transmission");
        add(lblTransmission, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, -1, -1));

        cbTransmission.setBackground(new java.awt.Color(245, 245, 245));
        cbTransmission.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        cbTransmission.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manual", "Automatic", " " }));
        add(cbTransmission, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 290, 40));

        lblVehicleType.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblVehicleType.setText("Vehicle Type");
        add(lblVehicleType, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, -1, -1));

        cbVehicleType1.setBackground(new java.awt.Color(245, 245, 245));
        cbVehicleType1.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        cbVehicleType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedan", "SUV", "Hatchback", "Van", "Pickup", "Off-road", "Sports", "Convertible", "Crossover", "Wagon", "Muscle", "Roadster", "Cabriolet", "Limousine" }));
        cbVehicleType1.setMinimumSize(new java.awt.Dimension(109, 27));
        cbVehicleType1.setPreferredSize(new java.awt.Dimension(109, 27));
        add(cbVehicleType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 480, 320, 40));

        lblFuelType.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblFuelType.setText("Fuel Type");
        add(lblFuelType, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, -1, -1));

        cbFuelType.setBackground(new java.awt.Color(245, 245, 245));
        cbFuelType.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        cbFuelType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gasoline", "Diesel", "Electric", "Hybrid" }));
        cbFuelType.setMinimumSize(new java.awt.Dimension(109, 27));
        cbFuelType.setPreferredSize(new java.awt.Dimension(109, 27));
        add(cbFuelType, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 290, 40));

        lblSeats.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblSeats.setText("Seats");
        add(lblSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, -1, -1));

        cbSeats.setBackground(new java.awt.Color(245, 245, 245));
        cbSeats.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        cbSeats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "4", "5", "7", "8", "12", "16" }));
        cbSeats.setMinimumSize(new java.awt.Dimension(109, 27));
        cbSeats.setPreferredSize(new java.awt.Dimension(109, 27));
        add(cbSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 310, 40));

        btnCreateListing.setBackground(new java.awt.Color(156, 142, 128));
        btnCreateListing.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        btnCreateListing.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateListing.setText("Create Listing");
        btnCreateListing.setContentAreaFilled(false);
        btnCreateListing.setPreferredSize(new java.awt.Dimension(200, 50));
        btnCreateListing.addActionListener(this::btnCreateListingActionPerformed);
        add(btnCreateListing, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 630, 400, -1));

        lblPlateNumber.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblPlateNumber.setText("Plate Number");
        add(lblPlateNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));

        txtPlateNumber.setBackground(new java.awt.Color(245, 245, 245));
        txtPlateNumber.setColumns(35);
        txtPlateNumber.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        txtPlateNumber.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 45, 5, 5));
        txtPlateNumber.setMargin(new java.awt.Insets(5, 35, 5, 10));
        txtPlateNumber.setMinimumSize(new java.awt.Dimension(400, 45));
        txtPlateNumber.setOpaque(true);
        txtPlateNumber.addActionListener(this::txtPlateNumberActionPerformed);
        add(txtPlateNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 290, 40));

        lblMileage.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblMileage.setText("Mileage");
        add(lblMileage, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, -1, -1));

        txtMileage.setBackground(new java.awt.Color(245, 245, 245));
        txtMileage.setColumns(35);
        txtMileage.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        txtMileage.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 45, 5, 5));
        txtMileage.setMargin(new java.awt.Insets(5, 35, 5, 10));
        txtMileage.setMinimumSize(new java.awt.Dimension(400, 45));
        txtMileage.setOpaque(true);
        txtMileage.addActionListener(this::txtMileageActionPerformed);
        add(txtMileage, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 570, 290, 40));

        lblColor.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblColor.setText("Color");
        add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, -1, -1));

        txtColor.setBackground(new java.awt.Color(245, 245, 245));
        txtColor.setColumns(35);
        txtColor.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        txtColor.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 45, 5, 5));
        txtColor.setMargin(new java.awt.Insets(5, 35, 5, 10));
        txtColor.setMinimumSize(new java.awt.Dimension(400, 45));
        txtColor.setOpaque(true);
        txtColor.addActionListener(this::txtColorActionPerformed);
        add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 310, 40));

        lblDriverOption.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblDriverOption.setText("Driver");
        add(lblDriverOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 540, -1, -1));

        cbDriverOption.setBackground(new java.awt.Color(245, 245, 245));
        cbDriverOption.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        cbDriverOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "With Driver", "Without Driver" }));
        cbDriverOption.setMinimumSize(new java.awt.Dimension(109, 27));
        cbDriverOption.setPreferredSize(new java.awt.Dimension(109, 27));
        add(cbDriverOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 570, 320, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void pnlImageUploadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlImageUploadMouseClicked
        // TODO add your handling code here:
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        javax.swing.filechooser.FileNameExtensionFilter filter
                = new javax.swing.filechooser.FileNameExtensionFilter("Images", "jpg", "png", "jpeg");
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(this);

        if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File selectedFile = fileChooser.getSelectedFile();

            // 1. Save path to a class variable
            this.selectedImagePath = carrentalsystem.utils.ImageUtil.copyImage(selectedFile);

            if (selectedImagePath != null) {
                // 2. HIDE the instructions
                lblImageIcon.setVisible(false);
                lblUploadText.setVisible(false);

                // 3. SHOW and update the preview label
                lblPhotoPreview.setVisible(true);
                carrentalsystem.utils.ImageUtil.applyScaledImage(lblPhotoPreview, selectedImagePath, 450, 250);

                // 4. Refresh to ensure the new image paints
                pnlImageUpload.revalidate();
                pnlImageUpload.repaint();
            }
        }
    }//GEN-LAST:event_pnlImageUploadMouseClicked

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandActionPerformed

    private void txtBrandFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBrandFocusGained
        // TODO add your handling code here:
        if (txtBrand.getText().equals("e.g., Toyota")) {
            txtBrand.setText("");
            txtBrand.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_txtBrandFocusGained

    private void txtBrandFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBrandFocusLost
        // TODO add your handling code here:
        if (txtBrand.getText().isEmpty()) {
            txtBrand.setText("e.g., Toyota");
            txtBrand.setForeground(new java.awt.Color(180, 180, 180)); // Grey placeholder
        }
    }//GEN-LAST:event_txtBrandFocusLost

    private void txtBasePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBasePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBasePriceActionPerformed

    private void txtModelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtModelFocusGained
        // TODO add your handling code here:
        if (txtModel.getText().equals("e.g., Vios")) {
            txtModel.setText("");
            txtModel.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_txtModelFocusGained

    private void txtModelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtModelFocusLost
        // TODO add your handling code here:
        if (txtModel.getText().isEmpty()) {
            txtModel.setText("e.g., Vios");
            txtModel.setForeground(new java.awt.Color(180, 180, 180));
        }
    }//GEN-LAST:event_txtModelFocusLost

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed

    private void btnCreateListingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateListingActionPerformed

        carrentalsystem.models.User user = carrentalsystem.core.SessionManager.getCurrentUser();
        if (user == null) {
            return;
        }

        // 1. Safety check for NEW listings limit (Only for FREE users)
        if (currentEditingCarId == -1 && "FREE".equalsIgnoreCase(user.getTier())) {
            try {
                int count = new carrentalsystem.services.CarService().countUserListings(user.getUserId());
                if (count >= 5) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Limit reached! Free accounts are restricted to 5 listings.\nUpgrade to PRO for unlimited listings.");
                    return;
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        // 2. Extract Data from UI
        String brand = txtBrand.getText().trim();
        String model = txtModel.getText().trim();
        String priceStr = txtBasePrice.getText().trim();
        String description = txtDescription.getText().trim();
        String plateNumber = txtPlateNumber.getText().trim();
        String color = txtColor.getText().trim();
        String mileageStr = txtMileage.getText().trim();

        // Convert Driver Option String to Boolean
        String driverOption = cbDriverOption.getSelectedItem().toString();
        boolean hasDriver = driverOption.equalsIgnoreCase("Yes") || driverOption.equalsIgnoreCase("With Driver");

        // 3. Validation - Ensure no critical fields are empty
        if (brand.isEmpty() || brand.equals("e.g., Toyota") || model.isEmpty()
                || plateNumber.isEmpty() || color.isEmpty() || mileageStr.isEmpty()
                || priceStr.isEmpty() || selectedImagePath == null) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please fill in all fields (Plate, Color, Mileage, Price) and upload a car photo.");
            return;
        }

        try {
            // 4. Populate the Car object
            carrentalsystem.models.Car carObj = new carrentalsystem.models.Car();

            carObj.setOwnerId(user.getUserId());
            carObj.setBrand(brand);
            carObj.setModel(model);
            carObj.setBasePrice(Double.parseDouble(priceStr));
            carObj.setDescription(description);
            carObj.setImagePath(selectedImagePath);

            // Map New Technical Fields
            carObj.setPlateNumber(plateNumber);
            carObj.setColor(color);
            carObj.setHasDriver(hasDriver);

            // Use setMileage if your model uses that name, or setMileageLimit based on your Car.java
            // Based on your previous files, I'm using the Integer conversion here:
            carObj.setMileageLimit(Integer.parseInt(mileageStr));

            // Map ComboBoxes correctly
            carObj.setSeats(Integer.parseInt(cbSeats.getSelectedItem().toString()));
            carObj.setTransmission(cbTransmission.getSelectedItem().toString());
            carObj.setFuelType(cbFuelType.getSelectedItem().toString());
            carObj.setCondition(cbCondition.getSelectedItem().toString());

            // Fix: setType should come from cbVehicleType, not cbDriverOption
            carObj.setType(cbVehicleType1.getSelectedItem().toString());

            carObj.setStatus("PENDING_APPROVAL");
            carObj.setPriority(false);

            // 5. Database Operations
            carrentalsystem.services.CarService carService = new carrentalsystem.services.CarService();

            if (currentEditingCarId == -1) {
                // Adding New Car
                int generatedId = carService.addCar(carObj);
                if (generatedId != -1) {
                    carObj.setCarId(generatedId);
                    javax.swing.JOptionPane.showMessageDialog(this, "Listing created successfully!\nPending for admin approval.");
                }
            } else {
                // Updating Existing Car
                carObj.setCarId(currentEditingCarId);
                carService.updateCar(carObj);
                javax.swing.JOptionPane.showMessageDialog(this, "Listing updated successfully!");
            }

            // 6. Refresh UI and Navigate
            if (dashboard != null) {
                dashboard.refreshCarFeed();
                // Automatically show the details of the car just created/edited
                dashboard.showCarDetails(carObj);
            }

            // Reset Form
            currentEditingCarId = -1;
            btnCreateListing.setText("Create Listing");
            clearForm();

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Price and Mileage must be valid numbers.");
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "An error occurred: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCreateListingActionPerformed

    private void cbConditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbConditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbConditionActionPerformed

    private void txtDescriptionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescriptionFocusGained
        // TODO add your handling code here:
        if (txtDescription.getText().equals("Tell renters what makes your car special.")) {
            txtDescription.setText("");
            txtDescription.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_txtDescriptionFocusGained

    private void txtDescriptionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescriptionFocusLost
        // TODO add your handling code here:
        if (txtDescription.getText().trim().isEmpty()) {
            txtDescription.setText("Tell renters what makes your car special.");
            txtDescription.setForeground(new java.awt.Color(180, 180, 180)); // Light grey
        }
    }//GEN-LAST:event_txtDescriptionFocusLost

    private void txtPlateNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlateNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlateNumberActionPerformed

    private void txtMileageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMileageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMileageActionPerformed

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    public void setDashboard(MainDashboard dashboard) {
        this.dashboard = dashboard;
    }

    @Override
    protected void paintComponent(java.awt.Graphics g) {
        java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
        g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

        // Paint the white rounded background
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30);

        g2.dispose();
        super.paintComponent(g);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateListing;
    private javax.swing.JComboBox<String> cbCondition;
    private javax.swing.JComboBox<String> cbDriverOption;
    private javax.swing.JComboBox<String> cbFuelType;
    private javax.swing.JComboBox<String> cbSeats;
    private javax.swing.JComboBox<String> cbTransmission;
    private javax.swing.JComboBox<String> cbVehicleType1;
    private javax.swing.JLabel lblBasePrice;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblCondition;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblDriverOption;
    private javax.swing.JLabel lblFuelType;
    private javax.swing.JLabel lblGenInfo;
    private javax.swing.JLabel lblImageIcon;
    private javax.swing.JLabel lblMileage;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblPhotoPreview;
    private javax.swing.JLabel lblPlateNumber;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTransmission;
    private javax.swing.JLabel lblUploadText;
    private javax.swing.JLabel lblVehicleType;
    private javax.swing.JPanel pnlImageUpload;
    private javax.swing.JScrollPane spDescription;
    private javax.swing.JTextField txtBasePrice;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtMileage;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtPlateNumber;
    // End of variables declaration//GEN-END:variables
}
