/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carrentalsystem.ui.user;


/**
 *
 * @author Sheanne
 */
public class CarCardPanel extends javax.swing.JPanel {

public void setCarDetails(String name, String price, String type) {
    lblCarName.setText(name);
    lblPrice.setText(price);
    lblType.setText(type);
}



    /**
     * Creates new form CarCardPanel
     */
    public CarCardPanel() {
        initComponents();
        btnRent.setBorder(new RoundedBorder(30));
        this.setBorder(new RoundedBorder(15)); // 15 is the radius of the corners
btnRent.setBackground(new java.awt.Color(44, 37, 37));
btnRent.setForeground(java.awt.Color.WHITE);
btnRent.setContentAreaFilled(false);
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblCarImage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblPrice = new javax.swing.JLabel();
        lblCarName = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        btnRent = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        setMinimumSize(new java.awt.Dimension(280, 350));
        setPreferredSize(new java.awt.Dimension(280, 350));
        setLayout(new java.awt.BorderLayout());

        lblCarImage.setBackground(new java.awt.Color(255, 255, 255));
        lblCarImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCarImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCarImage.setOpaque(true);
        lblCarImage.setPreferredSize(new java.awt.Dimension(280, 180));
        add(lblCarImage, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblPrice.setText("Price");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 0, 0);
        jPanel1.add(lblPrice, gridBagConstraints);

        lblCarName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCarName.setText("Car Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 0, 0);
        jPanel1.add(lblCarName, gridBagConstraints);

        lblType.setText("Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 0, 0);
        jPanel1.add(lblType, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        btnRent.setBackground(new java.awt.Color(44, 37, 37));
        btnRent.setForeground(new java.awt.Color(255, 255, 255));
        btnRent.setText("Rent");
        add(btnRent, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRent;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCarImage;
    private javax.swing.JLabel lblCarName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblType;
    // End of variables declaration//GEN-END:variables
}
