/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package carrentalsystem.ui.user;

/**
 *
 * @author macbookairm1grey
 */
public class CarCardPanel extends javax.swing.JPanel {

    /**
     * Creates new form CarCardPanel
     */
    public CarCardPanel() {
        initComponents();
    }
    
    /**
     * Updates the card UI with data from a Car and its Owner.
     *
     * @param car The car model instance
     * @param owner The user model instance (the car owner)
     */
    public void setCarData(carrentalsystem.models.Car car, carrentalsystem.models.User owner) {
        // 1. Set Vehicle Details
        lblTitle.setText(car.getBrand() + " " + car.getModel());
        lblPrice.setText("PHP " + String.format("%,.0f", car.getBasePrice()) + "/DAY");

        // 2. Set Dynamic Location from Owner Profile
        if (owner != null && owner.getCity() != null && owner.getProvince() != null) {
            lblLocation.setText(owner.getCity() + ", " + owner.getProvince());
        } else {
            lblLocation.setText("Location not set");
        }

        // 3. Load and Scale the Image
        carrentalsystem.utils.ImageUtil.applyScaledImage(lblImage, car.getImagePath(), 280, 200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblImage = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();

        setBackground(new java.awt.Color(223, 208, 209));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(280, 400));
        setLayout(new java.awt.GridBagLayout());

        lblImage.setText("Image");
        lblImage.setPreferredSize(new java.awt.Dimension(280, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(lblImage, gridBagConstraints);

        lblPrice.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(45, 36, 34));
        lblPrice.setText("Price");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 0, 10);
        add(lblPrice, gridBagConstraints);

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(45, 36, 34));
        lblTitle.setText("Brand & Model");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 10);
        add(lblTitle, gridBagConstraints);

        lblLocation.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblLocation.setForeground(new java.awt.Color(120, 120, 120));
        lblLocation.setText("Location");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 10, 10);
        add(lblLocation, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
