/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package carrentalsystem.ui.user;
import java.awt.*;
import java.awt.geom.RoundRectangle2D;
import javax.swing.*;
/**
 *
 * @author macbookairm1grey
 */
public class CarDetailsPanel extends javax.swing.JPanel {

    /**
     * Creates new form CarDetailsPanel
     */
    private MainDashboard dashboard;
    private carrentalsystem.models.Car currentCar;                           
    private carrentalsystem.services.UserService userService = new carrentalsystem.services.UserService(); // ← ADD
    
    public CarDetailsPanel() {
        initComponents();
        spDescription.setBorder(null);
        
        // Restore dark button color (initComponents overrides the anonymous initializer)
        btnRentNow.setBackground(new java.awt.Color(98, 89, 85));
        btnRentNow.setForeground(java.awt.Color.WHITE);

        // Spec pills need opaque=false for rounded painting to show
        lblTransmission.setOpaque(false);
        lblSeats.setOpaque(false);
        lblFuel.setOpaque(false);
        lblCondition.setOpaque(false);
        
        // Owner label
        lblOwnerName.setOpaque(false);
        lblOwnerName.setBackground(new java.awt.Color(240, 240, 240));
        lblOwnerName.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 12, 4, 12));

        // Fix 3: Set explicit size
        setPreferredSize(new java.awt.Dimension(1100, 700));
        setMinimumSize(new java.awt.Dimension(1100, 700));
        
    }
    
    public void setCarDetails(carrentalsystem.models.Car car) {
        if (car == null) return;
        
        // Save the car to class variable
        this.currentCar = car;
        
        // Title (Brand + Model)
        lblTitle.setText(car.getBrand().toUpperCase() + " " + car.getModel().toUpperCase());
        lblOwnerName.setText("Listed by: loading...");
        new Thread(() -> {
            try {
                carrentalsystem.models.User owner = userService.getUserById(car.getOwnerId());

                // Build the display string
                String displayName;
                if (owner != null && owner.getFullName() != null && !owner.getFullName().isBlank()) {
                    displayName = "Listed by: " + owner.getFullName();
                } else {
                    displayName = "Listed by: Unknown";
                }

                // Always update Swing components on the Event Dispatch Thread
                javax.swing.SwingUtilities.invokeLater(() -> lblOwnerName.setText(displayName));

            } catch (Exception e) {
                javax.swing.SwingUtilities.invokeLater(() -> lblOwnerName.setText("Listed by: Unknown"));
                System.err.println("[CarDetailsPanel] Could not load owner: " + e.getMessage());
            }
        }).start();

        // Price (Dynamic value + fixed "/day")
        // This formats 2500 into 2,500.00
        String formattedPrice = String.format("%,.2f", car.getBasePrice());
        lblPriceValue.setText("PHP " + formattedPrice + "/day");
        
        // Owner/lister name — uses car.getOwnerId() mapped to a name via your service
        // For now set a placeholder; replace with real owner lookup when UserService is ready
        lblOwnerName.setText("Listed by: Car Owner");

        // Specs (Capsules)
        lblTransmission.setText(car.getTransmission());
        lblSeats.setText(car.getSeats() + " Seaters");
        lblFuel.setText(car.getFuelType());
        lblCondition.setText(car.getCondition());

        // Description
        taDescription.setText(car.getDescription());

        // 5. Image Loading
        if (car.getImagePath() != null && !car.getImagePath().isEmpty()) {
            carrentalsystem.utils.ImageUtil.applyScaledImage(lblCarImage, car.getImagePath(), 560, 240);
        }
    }

    public void setDashboard(MainDashboard dashboard) {
        this.dashboard = dashboard;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCarImage = new javax.swing.JLabel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // Create a rounded rectangle clip (30px radius)
                java.awt.geom.RoundRectangle2D roundedRect = new java.awt.geom.RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 30, 30);
                g2.setClip(roundedRect);

                super.paintComponent(g2);
                g2.dispose();
            }
        };
        lblTitle = new javax.swing.JLabel();
        lblPriceHeader = new javax.swing.JLabel();
        lblPriceValue = new javax.swing.JLabel();
        lblOwnerName = new javax.swing.JLabel();
        pnlSpecRow = new javax.swing.JPanel();
        lblTransmission = new javax.swing.JLabel() {
            {
                setOpaque(false); // Make background transparent so we can paint the round shape
                setBackground(new java.awt.Color(245, 245, 245)); // Light grey
                // Padding: top, left, bottom, right (45px left for the icon)
                setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 45, 5, 15));
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING,
                    java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // Frosted glass — semi-transparent dark brown fill
                g2.setColor(new java.awt.Color(45, 36, 34, 160));
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30);

                // Subtle lighter border stroke for the glass edge
                g2.setColor(new java.awt.Color(255, 255, 255, 55));
                g2.setStroke(new java.awt.BasicStroke(1.2f));
                g2.drawRoundRect(1, 1, getWidth() - 2, getHeight() - 2, 30, 30);

                g2.dispose();
                super.paintComponent(g);
            }
        };
        lblSeats = new javax.swing.JLabel() {
            {
                setOpaque(false); // Make background transparent so we can paint the round shape
                setBackground(new java.awt.Color(245, 245, 245)); // Light grey
                // Padding: top, left, bottom, right (45px left for the icon)
                setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 45, 5, 15));
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING,
                    java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // Frosted glass — semi-transparent dark brown fill
                g2.setColor(new java.awt.Color(45, 36, 34, 160));
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30);

                // Subtle lighter border stroke for the glass edge
                g2.setColor(new java.awt.Color(255, 255, 255, 55));
                g2.setStroke(new java.awt.BasicStroke(1.2f));
                g2.drawRoundRect(1, 1, getWidth() - 2, getHeight() - 2, 30, 30);

                g2.dispose();
                super.paintComponent(g);
            }
        };
        lblFuel = new javax.swing.JLabel() {
            {
                setOpaque(false); // Make background transparent so we can paint the round shape
                setBackground(new java.awt.Color(245, 245, 245)); // Light grey
                // Padding: top, left, bottom, right (45px left for the icon)
                setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 45, 5, 15));
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING,
                    java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // Frosted glass — semi-transparent dark brown fill
                g2.setColor(new java.awt.Color(45, 36, 34, 160));
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30);

                // Subtle lighter border stroke for the glass edge
                g2.setColor(new java.awt.Color(255, 255, 255, 55));
                g2.setStroke(new java.awt.BasicStroke(1.2f));
                g2.drawRoundRect(1, 1, getWidth() - 2, getHeight() - 2, 30, 30);

                g2.dispose();
                super.paintComponent(g);
            }
        };
        lblCondition = new javax.swing.JLabel() {
            {
                setOpaque(false); // Make background transparent so we can paint the round shape
                setBackground(new java.awt.Color(245, 245, 245)); // Light grey
                // Padding: top, left, bottom, right (45px left for the icon)
                setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 45, 5, 15));
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING,
                    java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // Frosted glass — semi-transparent dark brown fill
                g2.setColor(new java.awt.Color(45, 36, 34, 160));
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30);

                // Subtle lighter border stroke for the glass edge
                g2.setColor(new java.awt.Color(255, 255, 255, 55));
                g2.setStroke(new java.awt.BasicStroke(1.2f));
                g2.drawRoundRect(1, 1, getWidth() - 2, getHeight() - 2, 30, 30);

                g2.dispose();
                super.paintComponent(g);
            }
        };
        btnRentNow = new javax.swing.JButton() {
            {
                // 1. Basic Setup
                setOpaque(false);
                setContentAreaFilled(false);
                setFocusPainted(false);
                setBorderPainted(false);
                setForeground(java.awt.Color.WHITE);
                setBackground(new java.awt.Color(98, 89, 85)); // Your dark taupe color
                setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // 2. Paint Rounded Background
                // Change color slightly if the button is pressed
                if (getModel().isArmed()) {
                    g2.setColor(getBackground().darker());
                } else if (getModel().isRollover()) {
                    g2.setColor(new java.awt.Color(118, 109, 105)); // Slightly lighter hover color
                } else {
                    g2.setColor(getBackground());
                }

                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30);

                g2.dispose();
                super.paintComponent(g); // This draws the "RENT NOW" text
            }
        };
        lblDescriptionHeader = new javax.swing.JLabel();
        spDescription = new javax.swing.JScrollPane();
        taDescription = new javax.swing.JTextArea() {
            {
                setOpaque(false);
                setLineWrap(true);
                setWrapStyleWord(true);
                setBackground(new java.awt.Color(45, 36, 34));   // dark brown
                setForeground(new java.awt.Color(230, 220, 215)); // warm cream text
                setCaretColor(new java.awt.Color(230, 220, 215)); // cursor matches text
                setFont(new java.awt.Font("Helvetica Neue", java.awt.Font.PLAIN, 14));
                setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 18, 15, 18));
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING,
                    java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                // Fill rounded background with dark brown
                g2.setColor(new java.awt.Color(45, 36, 34));
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 24, 24);
                g2.dispose();
                super.paintComponent(g);
            }
        };

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCarImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCarImage.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lblCarImage.setPreferredSize(new java.awt.Dimension(560, 350));
        add(lblCarImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 560, 260));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitle.setText("Car Title Placeholder");
        lblTitle.setPreferredSize(new java.awt.Dimension(400, 50));
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 400, 50));

        lblPriceHeader.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblPriceHeader.setForeground(new java.awt.Color(102, 102, 102));
        lblPriceHeader.setText("Price");
        lblPriceHeader.setPreferredSize(new java.awt.Dimension(400, 40));
        add(lblPriceHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 400, 40));

        lblPriceValue.setFont(new java.awt.Font("Helvetica Neue", 1, 45)); // NOI18N
        lblPriceValue.setText("Price Value /day");
        lblPriceValue.setPreferredSize(new java.awt.Dimension(400, 45));
        add(lblPriceValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 400, 45));

        lblOwnerName.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblOwnerName.setForeground(new java.awt.Color(6, 6, 6));
        lblOwnerName.setText("Listed by: Owner Name");
        lblOwnerName.setPreferredSize(new java.awt.Dimension(400, 35));
        add(lblOwnerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 400, 35));

        pnlSpecRow.setBackground(new java.awt.Color(255, 255, 255));
        pnlSpecRow.setOpaque(false);
        pnlSpecRow.setPreferredSize(new java.awt.Dimension(800, 60));
        pnlSpecRow.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 7));

        lblTransmission.setBackground(new java.awt.Color(45, 36, 34));
        lblTransmission.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblTransmission.setForeground(new java.awt.Color(230, 220, 215));
        lblTransmission.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrentalsystem/ui/user/Icons/Transimission Type.png"))); // NOI18N
        lblTransmission.setText("jLabel1");
        lblTransmission.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        lblTransmission.setIconTextGap(10);
        lblTransmission.setPreferredSize(new java.awt.Dimension(150, 45));
        pnlSpecRow.add(lblTransmission);

        lblSeats.setBackground(new java.awt.Color(45, 36, 34));
        lblSeats.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblSeats.setForeground(new java.awt.Color(230, 220, 215));
        lblSeats.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrentalsystem/ui/user/Icons/Seaters.png"))); // NOI18N
        lblSeats.setText("jLabel1");
        lblSeats.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        lblSeats.setIconTextGap(10);
        lblSeats.setPreferredSize(new java.awt.Dimension(150, 45));
        pnlSpecRow.add(lblSeats);

        lblFuel.setBackground(new java.awt.Color(45, 36, 34));
        lblFuel.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblFuel.setForeground(new java.awt.Color(230, 220, 215));
        lblFuel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrentalsystem/ui/user/Icons/Fuel Type.png"))); // NOI18N
        lblFuel.setText("jLabel1");
        lblFuel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        lblFuel.setIconTextGap(10);
        lblFuel.setPreferredSize(new java.awt.Dimension(150, 45));
        pnlSpecRow.add(lblFuel);

        lblCondition.setBackground(new java.awt.Color(45, 36, 34));
        lblCondition.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblCondition.setForeground(new java.awt.Color(230, 220, 215));
        lblCondition.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrentalsystem/ui/user/Icons/Condition.png"))); // NOI18N
        lblCondition.setText("jLabel1");
        lblCondition.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        lblCondition.setIconTextGap(10);
        lblCondition.setPreferredSize(new java.awt.Dimension(150, 45));
        pnlSpecRow.add(lblCondition);

        btnRentNow.setBackground(new java.awt.Color(245, 245, 245));
        btnRentNow.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        btnRentNow.setText("RENT NOW");
        btnRentNow.setPreferredSize(new java.awt.Dimension(200, 50));
        btnRentNow.addActionListener(this::btnRentNowActionPerformed);
        pnlSpecRow.add(btnRentNow);

        add(pnlSpecRow, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 980, 60));

        lblDescriptionHeader.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblDescriptionHeader.setForeground(new java.awt.Color(45, 36, 34));
        lblDescriptionHeader.setText("Description");
        add(lblDescriptionHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        spDescription.setBorder(null);
        spDescription.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        spDescription.setOpaque(false);
        spDescription.setPreferredSize(new java.awt.Dimension(980, 150));

        taDescription.setEditable(false);
        taDescription.setBackground(new java.awt.Color(45, 36, 34));
        taDescription.setColumns(20);
        taDescription.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        taDescription.setForeground(new java.awt.Color(230, 220, 215));
        taDescription.setRows(5);
        taDescription.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 18, 15, 18));
        taDescription.setCaretColor(new java.awt.Color(230, 220, 215));
        spDescription.setViewportView(taDescription);

        add(spDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 980, 150));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRentNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentNowActionPerformed
        // TODO add your handling code here:
        if (dashboard != null && currentCar != null) {
            // 1. Get the booking panel instance from the dashboard
            carrentalsystem.ui.user.BookingPanel bp = dashboard.getBookingPanel1();

            // 2. Pass the car data to the panel
            bp.prepareBooking(currentCar);

            // 3. Switch the card view
            java.awt.CardLayout cl = (java.awt.CardLayout) dashboard.getPnlMainContent().getLayout();
            cl.show(dashboard.getPnlMainContent(), "bookingCard");
        }
    }//GEN-LAST:event_btnRentNowActionPerformed

    @Override
    protected void paintComponent(java.awt.Graphics g) {
        java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
        g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING,
                java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
        // Soft shadow
        g2.setColor(new java.awt.Color(0, 0, 0, 15));
        g2.fillRoundRect(8, 8, getWidth() - 8, getHeight() - 8, 36, 36);
        // White card background
        g2.setColor(java.awt.Color.WHITE);
        g2.fillRoundRect(0, 0, getWidth() - 8, getHeight() - 8, 36, 36);
        g2.dispose();
        super.paintComponent(g);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRentNow;
    private javax.swing.JLabel lblCarImage;
    private javax.swing.JLabel lblCondition;
    private javax.swing.JLabel lblDescriptionHeader;
    private javax.swing.JLabel lblFuel;
    private javax.swing.JLabel lblOwnerName;
    private javax.swing.JLabel lblPriceHeader;
    private javax.swing.JLabel lblPriceValue;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTransmission;
    private javax.swing.JPanel pnlSpecRow;
    private javax.swing.JScrollPane spDescription;
    private javax.swing.JTextArea taDescription;
    // End of variables declaration//GEN-END:variables
}
