/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package carrentalsystem.ui.user;

import carrentalsystem.utils.ImageUtil;

/**
 *
 * @author macbookairm1grey
 */
public class HeaderPanel extends javax.swing.JPanel {

    /**
     * Creates new form HeaderPanel
     */
    private Runnable burgerAction;
    private Runnable burgerExitAction;
    private Runnable notificationsAction;
    private Runnable profileAction;
    private int unreadCount = 0;
    private java.util.function.Consumer<String> searchCallback;
    
    public HeaderPanel() {
        initComponents();
        // Search Bar styling[cite: 8]
        txtSearch.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        txtSearch.setOpaque(false);
        txtSearch.setBackground(new java.awt.Color(0, 0, 0, 0));
    }
    
    public void setBurgerAction(Runnable action) {
        this.burgerAction = action;
    }

    public void setBurgerExitAction(Runnable action) {
        this.burgerExitAction = action;
    }

    public void setUnreadCount(int count) {
        System.out.println("[DEBUG] Header received count: " + count);
        this.unreadCount = count;
        btnNotifications.repaint(); // Force a redraw to show/hide the dot
    }
    
    public void setNotificationsAction(Runnable action) {
        this.notificationsAction = action;
    }
    
    public void setProfileAction(Runnable action) {
        this.profileAction = action;
        btnProfile.addActionListener(e -> {
            if (profileAction != null) {
                profileAction.run();
            }
        });
    }
    public void updateProfileIcon(String imagePath) {
        int size = 40; // Match the button's visual size

        if (imagePath != null && !imagePath.isEmpty()) {
            // Load the user's custom photo
            ImageUtil.applyScaledImage(btnProfile, imagePath, size, size);
        } else {
            // Load your default "user" icon from resources
            try {
                java.net.URL defaultIconUrl = getClass().getResource("/carrentalsystem/ui/user/Icons/DefaultProfile.png");
                if (defaultIconUrl != null) {
                    javax.swing.ImageIcon defaultIcon = new javax.swing.ImageIcon(defaultIconUrl);
                    java.awt.Image img = defaultIcon.getImage().getScaledInstance(size, size, java.awt.Image.SCALE_SMOOTH);
                    btnProfile.setIcon(new javax.swing.ImageIcon(img));
                }
            } catch (Exception e) {
                System.err.println("Default profile icon not found!");
            }
        }
    }
    
    public void setSearchAction(java.util.function.Consumer<String> action) {
        this.searchCallback = action;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        txtSearch = new javax.swing.JTextField() {
            {
                // 1. THIS IS THE INTERNAL PADDING (Top, Left, Bottom, Right)
                // 20 pixels on the left will push the text away from the curve
                setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
                setOpaque(false);
                setBackground(new java.awt.Color(0, 0, 0, 0));
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);
                g2.dispose();
                super.paintComponent(g);
            }

            // REMOVED the empty setBorder method that was blocking your changes
        }
        ;
        btnBurgerMenu = new javax.swing.JButton();
        btnNotifications = new javax.swing.JButton() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g); // Draws the original bell icon

                if (unreadCount > 0) {
                    java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                    // Makes the red dot smooth
                    g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                    g2.setColor(java.awt.Color.RED);

                    // Draws the red dot at the top-right corner of your 50x51 button
                    g2.fillOval(getWidth() - 15, 5, 12, 12);
                    g2.dispose();
                }
            }
        };
        btnProfile = new javax.swing.JButton() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // This creates a circular clip based on the smallest dimension
                int diameter = Math.min(getWidth(), getHeight());
                java.awt.geom.Ellipse2D circle = new java.awt.geom.Ellipse2D.Double(0, 0, diameter, diameter);
                g2.setClip(circle);

                super.paintComponent(g2);
                g2.dispose();
            }
        };

        setBackground(new java.awt.Color(45, 36, 34));
        setPreferredSize(new java.awt.Dimension(1440, 65));
        setLayout(new java.awt.GridBagLayout());

        txtSearch.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(150, 150, 150));
        txtSearch.setText("Search");
        txtSearch.setPreferredSize(new java.awt.Dimension(400, 40));
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchFocusLost(evt);
            }
        });
        txtSearch.addActionListener(this::txtSearchActionPerformed);
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(13, 70, 12, 70);
        add(txtSearch, gridBagConstraints);

        btnBurgerMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrentalsystem/ui/user/Icons/Menu.png"))); // NOI18N
        btnBurgerMenu.setBorderPainted(false);
        btnBurgerMenu.setContentAreaFilled(false);
        btnBurgerMenu.setPreferredSize(new java.awt.Dimension(50, 51));
        btnBurgerMenu.addActionListener(this::btnBurgerMenuActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 60, 10, 0);
        add(btnBurgerMenu, gridBagConstraints);

        btnNotifications.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrentalsystem/ui/user/Icons/Notification.png"))); // NOI18N
        btnNotifications.setBorderPainted(false);
        btnNotifications.setContentAreaFilled(false);
        btnNotifications.setPreferredSize(new java.awt.Dimension(50, 51));
        btnNotifications.addActionListener(this::btnNotificationsActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 300, 5, 0);
        add(btnNotifications, gridBagConstraints);

        btnProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrentalsystem/ui/user/Icons/DefaultProfile.png"))); // NOI18N
        btnProfile.setBorderPainted(false);
        btnProfile.setContentAreaFilled(false);
        btnProfile.setPreferredSize(new java.awt.Dimension(50, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 30, 5, 52);
        add(btnProfile, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusGained
        // TODO add your handling code here:
        if (txtSearch.getText().equals("Search")) {
            txtSearch.setText("");
            txtSearch.setForeground(new java.awt.Color(0, 0, 0)); // Change text to black when typing
        }
    }//GEN-LAST:event_txtSearchFocusGained

    private void txtSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusLost
        // TODO add your handling code here:
        if (txtSearch.getText().isEmpty()) {
            txtSearch.setForeground(new java.awt.Color(150, 150, 150)); // Gray color
            txtSearch.setText("Search");
        }
    }//GEN-LAST:event_txtSearchFocusLost

    private void btnBurgerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBurgerMenuActionPerformed
        // TODO add your handling code here:
        if (burgerAction != null) {
            burgerAction.run();
        }
    }//GEN-LAST:event_btnBurgerMenuActionPerformed

    private void btnNotificationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificationsActionPerformed
        // TODO add your handling code here:
        if (notificationsAction != null) {
            notificationsAction.run();
        }
    }//GEN-LAST:event_btnNotificationsActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String query = txtSearch.getText().trim();
        if (searchCallback != null) {
            if (query.isEmpty() || query.equalsIgnoreCase("Search")) {
                searchCallback.accept("");
            } else {
                searchCallback.accept(query); 
            }
        }
    }//GEN-LAST:event_txtSearchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBurgerMenu;
    private javax.swing.JButton btnNotifications;
    private javax.swing.JButton btnProfile;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
