/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrentalsystem.ui.user;

import java.awt.Color;

/**
 *
 * @author macbookairm1grey
 */
public class MainDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainDashboard.class.getName());

    /**
     * Creates new form MainDashboard
     */
    public MainDashboard() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlMainContainer = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        btnBurgerIcon = new javax.swing.JButton();
        pnlRightActions = new javax.swing.JPanel();
        btnNotification = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        pnlSearchContainer = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField() {
            {
                // 1. THIS IS THE INTERNAL PADDING (Top, Left, Bottom, Right)
                // 20 pixels on the left will push the text away from the curve
                setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
                setOpaque(false);
                setBackground(new java.awt.Color(0, 0, 0, 0));
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);
                g2.dispose();
                super.paintComponent(g);
            }

            // REMOVED the empty setBorder method that was blocking your changes
        }
        ;

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1440, 1024));

        pnlMainContainer.setLayout(new java.awt.BorderLayout());

        pnlHeader.setBackground(new java.awt.Color(44, 37, 37));
        pnlHeader.setPreferredSize(new java.awt.Dimension(542, 70));
        pnlHeader.setLayout(new java.awt.BorderLayout());

        btnBurgerIcon.setText("Burger");
        btnBurgerIcon.setBorderPainted(false);
        btnBurgerIcon.setContentAreaFilled(false);
        btnBurgerIcon.setFocusPainted(false);
        btnBurgerIcon.setPreferredSize(new java.awt.Dimension(73, 60));
        pnlHeader.add(btnBurgerIcon, java.awt.BorderLayout.WEST);

        pnlRightActions.setOpaque(false);
        pnlRightActions.setPreferredSize(new java.awt.Dimension(200, 60));
        pnlRightActions.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnNotification.setText("Notification");
        btnNotification.setBorderPainted(false);
        btnNotification.setContentAreaFilled(false);
        btnNotification.setFocusPainted(false);
        btnNotification.setPreferredSize(new java.awt.Dimension(73, 60));
        pnlRightActions.add(btnNotification);

        btnProfile.setText("Profile");
        btnProfile.setBorderPainted(false);
        btnProfile.setContentAreaFilled(false);
        btnProfile.setFocusPainted(false);
        btnProfile.setPreferredSize(new java.awt.Dimension(73, 60));
        pnlRightActions.add(btnProfile);

        pnlHeader.add(pnlRightActions, java.awt.BorderLayout.EAST);

        pnlSearchContainer.setOpaque(false);
        pnlSearchContainer.setLayout(new java.awt.GridBagLayout());

        txtUsername.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        txtUsername.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        txtUsername.setPreferredSize(new java.awt.Dimension(300, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 50);
        pnlSearchContainer.add(txtUsername, gridBagConstraints);

        pnlHeader.add(pnlSearchContainer, java.awt.BorderLayout.CENTER);

        pnlMainContainer.add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(pnlMainContainer, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBurgerIcon;
    private javax.swing.JButton btnNotification;
    private javax.swing.JButton btnProfile;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMainContainer;
    private javax.swing.JPanel pnlRightActions;
    private javax.swing.JPanel pnlSearchContainer;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
