/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package carrentalsystem.ui.user;

/**
 *
 * @author macbookairm1grey
 */
public class SidebarPanel extends javax.swing.JPanel {

    /**
     * Creates new form SidebarPanel
     */
    public SidebarPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHome = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        lblMyLIsts = new javax.swing.JLabel();
        btnMyLists = new javax.swing.JButton();
        lblRents = new javax.swing.JLabel();
        btnRents = new javax.swing.JButton();
        lblInbox = new javax.swing.JLabel();
        btnInbox = new javax.swing.JButton();
        lblAnalytics = new javax.swing.JLabel();
        btnAnalytics = new javax.swing.JButton();
        lblReservations = new javax.swing.JLabel();
        btnReservations = new javax.swing.JButton();
        btnAddList = new javax.swing.JButton();
        lblSettings = new javax.swing.JLabel();
        btnSettings = new javax.swing.JButton();
        lblLogout = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        sptLine1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(45, 36, 34));
        setPreferredSize(new java.awt.Dimension(500, 1024));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHome.setText("jLabel1");
        lblHome.setPreferredSize(new java.awt.Dimension(50, 50));
        add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        btnHome.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Home");
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.setPreferredSize(new java.awt.Dimension(200, 50));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        btnHome.addActionListener(this::btnHomeActionPerformed);
        add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        lblMyLIsts.setText("jLabel1");
        lblMyLIsts.setPreferredSize(new java.awt.Dimension(50, 50));
        add(lblMyLIsts, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        btnMyLists.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btnMyLists.setForeground(new java.awt.Color(255, 255, 255));
        btnMyLists.setText("My Listings");
        btnMyLists.setBorderPainted(false);
        btnMyLists.setContentAreaFilled(false);
        btnMyLists.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMyLists.setPreferredSize(new java.awt.Dimension(200, 50));
        btnMyLists.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMyListsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMyListsMouseExited(evt);
            }
        });
        btnMyLists.addActionListener(this::btnMyListsActionPerformed);
        add(btnMyLists, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        lblRents.setText("jLabel1");
        lblRents.setPreferredSize(new java.awt.Dimension(50, 50));
        add(lblRents, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        btnRents.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btnRents.setForeground(new java.awt.Color(255, 255, 255));
        btnRents.setText("My Rentals");
        btnRents.setBorderPainted(false);
        btnRents.setContentAreaFilled(false);
        btnRents.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRents.setPreferredSize(new java.awt.Dimension(200, 50));
        btnRents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRentsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRentsMouseExited(evt);
            }
        });
        btnRents.addActionListener(this::btnRentsActionPerformed);
        add(btnRents, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        lblInbox.setText("jLabel1");
        lblInbox.setPreferredSize(new java.awt.Dimension(50, 50));
        add(lblInbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        btnInbox.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btnInbox.setForeground(new java.awt.Color(255, 255, 255));
        btnInbox.setText("Inbox");
        btnInbox.setBorderPainted(false);
        btnInbox.setContentAreaFilled(false);
        btnInbox.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInbox.setPreferredSize(new java.awt.Dimension(200, 50));
        btnInbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInboxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInboxMouseExited(evt);
            }
        });
        btnInbox.addActionListener(this::btnInboxActionPerformed);
        add(btnInbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        lblAnalytics.setText("jLabel1");
        lblAnalytics.setPreferredSize(new java.awt.Dimension(50, 50));
        add(lblAnalytics, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        btnAnalytics.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btnAnalytics.setForeground(new java.awt.Color(255, 255, 255));
        btnAnalytics.setText("Analytics");
        btnAnalytics.setBorderPainted(false);
        btnAnalytics.setContentAreaFilled(false);
        btnAnalytics.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAnalytics.setPreferredSize(new java.awt.Dimension(200, 50));
        btnAnalytics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAnalyticsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAnalyticsMouseExited(evt);
            }
        });
        btnAnalytics.addActionListener(this::btnAnalyticsActionPerformed);
        add(btnAnalytics, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));

        lblReservations.setText("jLabel1");
        lblReservations.setPreferredSize(new java.awt.Dimension(50, 50));
        add(lblReservations, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        btnReservations.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btnReservations.setForeground(new java.awt.Color(255, 255, 255));
        btnReservations.setText("Reservations");
        btnReservations.setBorderPainted(false);
        btnReservations.setContentAreaFilled(false);
        btnReservations.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReservations.setPreferredSize(new java.awt.Dimension(200, 50));
        btnReservations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReservationsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReservationsMouseExited(evt);
            }
        });
        btnReservations.addActionListener(this::btnReservationsActionPerformed);
        add(btnReservations, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, -1, -1));

        btnAddList.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btnAddList.setForeground(new java.awt.Color(255, 255, 255));
        btnAddList.setText("Add List");
        btnAddList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnAddList.setContentAreaFilled(false);
        btnAddList.setPreferredSize(new java.awt.Dimension(200, 50));
        btnAddList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddListMouseExited(evt);
            }
        });
        btnAddList.addActionListener(this::btnAddListActionPerformed);
        add(btnAddList, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, -1, -1));

        lblSettings.setText("jLabel1");
        lblSettings.setPreferredSize(new java.awt.Dimension(50, 50));
        add(lblSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 660, -1, -1));

        btnSettings.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btnSettings.setForeground(new java.awt.Color(255, 255, 255));
        btnSettings.setText("Settings");
        btnSettings.setBorderPainted(false);
        btnSettings.setContentAreaFilled(false);
        btnSettings.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSettings.setPreferredSize(new java.awt.Dimension(200, 50));
        btnSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSettingsMouseExited(evt);
            }
        });
        btnSettings.addActionListener(this::btnSettingsActionPerformed);
        add(btnSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 660, -1, -1));

        lblLogout.setText("jLabel1");
        lblLogout.setPreferredSize(new java.awt.Dimension(50, 50));
        add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 720, -1, -1));

        btnLogout.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setBorderPainted(false);
        btnLogout.setContentAreaFilled(false);
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogout.setPreferredSize(new java.awt.Dimension(200, 50));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        btnLogout.addActionListener(this::btnLogoutActionPerformed);
        add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 720, -1, -1));

        sptLine1.setPreferredSize(new java.awt.Dimension(300, 10));
        add(sptLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, -1, 170));
    }// </editor-fold>//GEN-END:initComponents

    private void btnMyListsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyListsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMyListsActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnInboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInboxActionPerformed

    private void btnRentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRentsActionPerformed

    private void btnAnalyticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalyticsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnalyticsActionPerformed

    private void btnReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservationsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReservationsActionPerformed

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        // TODO add your handling code here:
        btnHome.setContentAreaFilled(true); // Turn the background back on
        btnHome.setBackground(new java.awt.Color(65, 56, 54)); // Set the hover color
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); // Make it look clickable
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        // TODO add your handling code here:
        btnHome.setContentAreaFilled(false); // Turn the background off again
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnMyListsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMyListsMouseEntered
        // TODO add your handling code here:
        btnMyLists.setContentAreaFilled(true); 
        btnMyLists.setBackground(new java.awt.Color(65, 56, 54)); 
        btnMyLists.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); 
    }//GEN-LAST:event_btnMyListsMouseEntered

    private void btnMyListsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMyListsMouseExited
        // TODO add your handling code here:
        btnMyLists.setContentAreaFilled(false);
    }//GEN-LAST:event_btnMyListsMouseExited

    private void btnInboxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInboxMouseEntered
        // TODO add your handling code here:
        btnInbox.setContentAreaFilled(true); 
        btnInbox.setBackground(new java.awt.Color(65, 56, 54)); 
        btnInbox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); 
    }//GEN-LAST:event_btnInboxMouseEntered

    private void btnInboxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInboxMouseExited
        // TODO add your handling code here:
        btnInbox.setContentAreaFilled(false);
    }//GEN-LAST:event_btnInboxMouseExited

    private void btnRentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRentsMouseEntered
        // TODO add your handling code here:
        btnRents.setContentAreaFilled(true); 
        btnRents.setBackground(new java.awt.Color(65, 56, 54)); 
        btnRents.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); 
    }//GEN-LAST:event_btnRentsMouseEntered

    private void btnRentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRentsMouseExited
        // TODO add your handling code here:
        btnRents.setContentAreaFilled(false);
    }//GEN-LAST:event_btnRentsMouseExited

    private void btnAnalyticsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnalyticsMouseEntered
        // TODO add your handling code here:
        btnAnalytics.setContentAreaFilled(true); 
        btnAnalytics.setBackground(new java.awt.Color(65, 56, 54)); 
        btnAnalytics.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); 
    }//GEN-LAST:event_btnAnalyticsMouseEntered

    private void btnAnalyticsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnalyticsMouseExited
        // TODO add your handling code here:
        btnAnalytics.setContentAreaFilled(false);
    }//GEN-LAST:event_btnAnalyticsMouseExited

    private void btnReservationsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReservationsMouseEntered
        // TODO add your handling code here:
        btnReservations.setContentAreaFilled(true); 
        btnReservations.setBackground(new java.awt.Color(65, 56, 54)); 
        btnReservations.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); 
    }//GEN-LAST:event_btnReservationsMouseEntered

    private void btnReservationsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReservationsMouseExited
        // TODO add your handling code here:
        btnReservations.setContentAreaFilled(false);
    }//GEN-LAST:event_btnReservationsMouseExited

    private void btnAddListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddListMouseEntered
        // TODO add your handling code here:
        btnAddList.setContentAreaFilled(true); 
        btnAddList.setBackground(new java.awt.Color(65, 56, 54)); 
        btnAddList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); 
    }//GEN-LAST:event_btnAddListMouseEntered

    private void btnAddListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddListMouseExited
        // TODO add your handling code here:
        btnAddList.setContentAreaFilled(false);
    }//GEN-LAST:event_btnAddListMouseExited

    private void btnAddListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddListActionPerformed

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
        btnLogout.setContentAreaFilled(true); 
        btnLogout.setBackground(new java.awt.Color(65, 56, 54)); 
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); 
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        // TODO add your handling code here:
        btnLogout.setContentAreaFilled(false);
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingsMouseEntered
        // TODO add your handling code here:
        btnSettings.setContentAreaFilled(true); 
        btnSettings.setBackground(new java.awt.Color(65, 56, 54)); 
        btnSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); 
    }//GEN-LAST:event_btnSettingsMouseEntered

    private void btnSettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingsMouseExited
        // TODO add your handling code here:
        btnSettings.setContentAreaFilled(false);
    }//GEN-LAST:event_btnSettingsMouseExited

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSettingsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddList;
    private javax.swing.JButton btnAnalytics;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInbox;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMyLists;
    private javax.swing.JButton btnRents;
    private javax.swing.JButton btnReservations;
    private javax.swing.JButton btnSettings;
    private javax.swing.JLabel lblAnalytics;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblInbox;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblMyLIsts;
    private javax.swing.JLabel lblRents;
    private javax.swing.JLabel lblReservations;
    private javax.swing.JLabel lblSettings;
    private javax.swing.JSeparator sptLine1;
    // End of variables declaration//GEN-END:variables
}
