/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carrentalsystem.ui.admin;

/**
 *
 * @author EMY2025
 */
import java.awt.*;
import java.util.HashMap;
import java.util.Map;
public class ListingChart extends javax.swing.JPanel {
    private Map<String, Integer> data = new HashMap<>();

    
    public ListingChart() {
        initComponents();
        setOpaque(true);
    }
    
    // This method receives the real data from your user/database
    public void updateChart(Map<String, Integer> stats) {
        this.data = stats;
        repaint();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        if (data.isEmpty()) return;

        int x = 50;
        int width = 40;
        int maxCount = data.values().stream().max(Integer::compare).orElse(1);
        int chartHeight = getHeight() - 100;

        for (Map.Entry<String, Integer> entry : data.entrySet()) {
            int barHeight = (int) ((double) entry.getValue() / maxCount * chartHeight);

            g2.setColor(new Color(11, 213, 91)); // green bar
            g2.fillRect(x, getHeight() - barHeight - 40, width, barHeight);

            g2.setColor(Color.WHITE);
            g2.drawString(entry.getKey(), x, getHeight() - 20);
            g2.drawString(entry.getValue().toString(), x + 15, getHeight() - barHeight - 50);

            x += 80;
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(38, 38, 36));
        setPreferredSize(new java.awt.Dimension(400, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
