/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carrentalsystem.ui.admin;

/**
 *
 * @author User
 */
public class Listing extends javax.swing.JPanel {

    
    public Listing() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableContent = new javax.swing.JTable();
        TableContent.setRowHeight(80);
        HeaderPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
javax.swing.JPanel corner = new javax.swing.JPanel();
corner.setBackground(new java.awt.Color(48, 48, 46));

// 2. Set it as the corner component for the scroll pane
jScrollPane2.setCorner(javax.swing.JScrollPane.UPPER_RIGHT_CORNER, corner);
        
        // Fix this line in initComponents:
jPanel1 = new javax.swing.JPanel() {
    @Override
    protected void paintComponent(java.awt.Graphics g) {
        java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
        g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        // Use 48, 48, 46 for your dark theme as intended
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30);
        g2.dispose();
    }
};
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(48, 48, 46));
        setPreferredSize(new java.awt.Dimension(1000, 570));
        setLayout(new java.awt.BorderLayout());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        
        // Make the main scroll pane and its viewport transparent
jScrollPane2.setOpaque(false);
jScrollPane2.getViewport().setOpaque(false);
jScrollPane2.setBorder(null);

// Set the viewport background to match your theme just in case
jScrollPane2.getViewport().setBackground(new java.awt.Color(48, 48, 46));

// Access the vertical scroll bar and remove its background
jScrollPane2.getVerticalScrollBar().setOpaque(false);
jScrollPane2.getVerticalScrollBar().setBackground(new java.awt.Color(48, 48, 46));
jScrollPane2.getVerticalScrollBar().setBorder(javax.swing.BorderFactory.createEmptyBorder());

// Make the scroll bar thinner for a modern look
jScrollPane2.getVerticalScrollBar().setPreferredSize(new java.awt.Dimension(8, 0));

// Optional: Hide the arrow buttons (top and bottom)
jScrollPane2.getVerticalScrollBar().setUI(new javax.swing.plaf.basic.BasicScrollBarUI() {
    @Override
    protected void configureScrollBarColors() {
        this.thumbColor = new java.awt.Color(100, 100, 100); // Change the drag handle color
    }
    @Override
    protected javax.swing.JButton createDecreaseButton(int orientation) {
        return createZeroButton();
    }
    @Override
    protected javax.swing.JButton createIncreaseButton(int orientation) {
        return createZeroButton();
    }
    private javax.swing.JButton createZeroButton() {
        javax.swing.JButton jbutton = new javax.swing.JButton();
        jbutton.setPreferredSize(new java.awt.Dimension(0, 0));
        jbutton.setMinimumSize(new java.awt.Dimension(0, 0));
        jbutton.setMaximumSize(new java.awt.Dimension(0, 0));
        return jbutton;
    }
});

        TableContent.setBackground(new java.awt.Color(43, 43, 43));
        TableContent.setForeground(new java.awt.Color(255, 255, 255));
        TableContent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car", "Owner", "Rate", "Status", "Status"
            }
        ));
        TableContent.setGridColor(new java.awt.Color(255, 255, 255));
        TableContent.setPreferredSize(new java.awt.Dimension(610, 500));
        TableContent.setShowVerticalLines(false);
        jScrollPane2.setViewportView(TableContent);
        if (TableContent.getColumnModel().getColumnCount() > 0) {
            TableContent.getColumnModel().getColumn(0).setPreferredWidth(350);
        }

        add(jScrollPane2, java.awt.BorderLayout.CENTER);

        HeaderPanel.setBackground(new java.awt.Color(48, 48, 46));
        HeaderPanel.setMaximumSize(new java.awt.Dimension(32767, 80));
        HeaderPanel.setPreferredSize(new java.awt.Dimension(900, 80));
        HeaderPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Listing Approvals");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        HeaderPanel.add(jLabel1, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(229, 192, 123));
        jPanel1.setForeground(new java.awt.Color(229, 192, 123));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel3.setBackground(new java.awt.Color(61, 52, 40));
        
        jPanel1.setLayout(new java.awt.GridBagLayout());
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(61, 52, 40));
        jLabel3.setText("5 Pendings");
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 50; // Horizontal padding
        gridBagConstraints.ipady = 15; // Vertical padding
        jPanel1.add(jLabel3, gridBagConstraints);
        
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);

        HeaderPanel.add(jPanel1, gridBagConstraints);
        
        // 2. Ensure it is rounded
jPanel1.setOpaque(false); // MUST be false to see rounded corners
add(HeaderPanel, java.awt.BorderLayout.NORTH);
jPanel1.setBackground(new java.awt.Color(229, 192, 123));

        add(HeaderPanel, java.awt.BorderLayout.NORTH);
        
        // --- ScrollPane Configuration ---
        jScrollPane2.setBackground(new java.awt.Color(48, 48, 46));
        jScrollPane2.getViewport().setBackground(new java.awt.Color(48, 48, 46));
        
        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder());

        // --- Table Configuration ---
        TableContent.setBackground(new java.awt.Color(43, 43, 43));
        TableContent.setForeground(new java.awt.Color(255, 255, 255));
        TableContent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // Table body font
        TableContent.setRowHeight(80);
        
        // --- Header Configuration ---
        javax.swing.table.JTableHeader header = TableContent.getTableHeader();
        header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 24)); //
        header.setBackground(new java.awt.Color(48, 48, 46)); //
        header.setForeground(java.awt.Color.WHITE); //
        header.setPreferredSize(new java.awt.Dimension(header.getWidth(), 50));
        
        TableContent.getTableHeader().setDefaultRenderer(new javax.swing.table.DefaultTableCellRenderer() {
    @Override
    public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
            boolean isSelected, boolean hasFocus, int row, int column) {
        super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        setBackground(new java.awt.Color(48, 48, 46));
        setForeground(java.awt.Color.WHITE);
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, java.awt.Color.GRAY)); // Subtle grid line
        return this;
    }
});
        
        // Create a custom renderer for the table header
javax.swing.table.DefaultTableCellRenderer headerRenderer = new javax.swing.table.DefaultTableCellRenderer() {
    @Override
    public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
            boolean isSelected, boolean hasFocus, int row, int column) {
        
        super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        
        // Set the dark theme background and white text
        setBackground(new java.awt.Color(48, 48, 46));
        setForeground(java.awt.Color.WHITE);
        
        // Center the text horizontally
        setHorizontalAlignment(javax.swing.JLabel.CENTER);
        
        // Optional: Add a subtle border between header cells to match your grid
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(80, 80, 80)));
        
        return this;
    }
};

// Apply the custom renderer and the Segoe UI 24 Plain font to the header
TableContent.getTableHeader().setDefaultRenderer(headerRenderer);
TableContent.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 24));
TableContent.getTableHeader().setPreferredSize(new java.awt.Dimension(100, 50)); // Ensure it's tall enough for 24pt
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JTable TableContent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel badgeLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
