/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carrentalsystem.ui.admin;

/**
 *
 * @author User
 */
public class SupportUiAdmin extends javax.swing.JPanel {

    /**
     * Creates new form SupportUiAdmin
     */
    public SupportUiAdmin() {
        initComponents();
        
        java.awt.Color themeColor = new java.awt.Color(48, 48, 46);
        java.awt.Color thumbColor = new java.awt.Color(100, 100, 100);
    
    // 1. Sync all background colors
    this.setBackground(themeColor); 
    HeaderPanel.setBackground(themeColor); 
    jScrollPane1.setBackground(themeColor);
    jScrollPane1.getViewport().setBackground(themeColor);
    TableContent.setBackground(themeColor);
    
    // 2. Table behavior and borders
    TableContent.setFillsViewportHeight(true); 
    TableContent.setForeground(java.awt.Color.WHITE);
    TableContent.setGridColor(new java.awt.Color(60, 60, 60)); 
    TableContent.setShowGrid(true);
    TableContent.setBorder(null);

    // 3. Remove ScrollPane borders completely
    jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    jScrollPane1.setViewportBorder(null);
    

// Create a custom renderer for the header
// Create a custom renderer for the header
javax.swing.table.DefaultTableCellRenderer headerRenderer = new javax.swing.table.DefaultTableCellRenderer() {
    @Override
    public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
            boolean isSelected, boolean hasFocus, int row, int column) {
        
        super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        
        // 1. SET FONT HERE - This is the missing piece
        setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 24));
        
        // Maintain your dark theme
        setBackground(new java.awt.Color(48, 48, 46));
        setForeground(java.awt.Color.WHITE);
        
        // Center the text
        setHorizontalAlignment(javax.swing.JLabel.CENTER);
        
        // Remove borders
        //setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(60, 60, 60)));
        setBorder(null);
        
        return this;
    }
};

// Apply the Segoe UI 24 Plain font and the custom renderer to the header
TableContent.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 24));
TableContent.getTableHeader().setDefaultRenderer(headerRenderer);

// Set header height to accommodate the larger 24pt font
TableContent.getTableHeader().setPreferredSize(new java.awt.Dimension(100, 50));

        jScrollPane1.getVerticalScrollBar().setUI(new javax.swing.plaf.basic.BasicScrollBarUI() {
    @Override
    protected void configureScrollBarColors() {
        // This sets the color of the dragging handle
        this.thumbColor = new java.awt.Color(100, 100, 100);
        // This sets the background color of the bar to match your panel
        this.trackColor = new java.awt.Color(48, 48, 46);
    }

    @Override
    protected javax.swing.JButton createDecreaseButton(int orientation) {
        return createZeroButton(); // Removes the top arrow
    }

    @Override
    protected javax.swing.JButton createIncreaseButton(int orientation) {
        return createZeroButton(); // Removes the bottom arrow
    }

    private javax.swing.JButton createZeroButton() {
        javax.swing.JButton jbutton = new javax.swing.JButton();
        jbutton.setPreferredSize(new java.awt.Dimension(0, 0));
        jbutton.setMinimumSize(new java.awt.Dimension(0, 0));
        jbutton.setMaximumSize(new java.awt.Dimension(0, 0));
        return jbutton;
    }
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        HeaderPanel = new javax.swing.JPanel();
        SupportTickets = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(getBackground());
                // The value 30 creates the perfect 'pill' arc
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30);
                super.paintComponent(g);
                g2.dispose();
            }
        };
        jScrollPane1 = new javax.swing.JScrollPane();
        TableContent = new javax.swing.JTable();

        setBackground(new java.awt.Color(43, 43, 43));
        setPreferredSize(new java.awt.Dimension(1000, 570));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HeaderPanel.setBackground(new java.awt.Color(43, 43, 43));
        HeaderPanel.setMaximumSize(new java.awt.Dimension(32767, 80));
        HeaderPanel.setMinimumSize(new java.awt.Dimension(384, 43));
        HeaderPanel.setPreferredSize(new java.awt.Dimension(900, 80));
        HeaderPanel.setLayout(new java.awt.GridBagLayout());

        SupportTickets.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        SupportTickets.setForeground(new java.awt.Color(255, 255, 255));
        SupportTickets.setText("Support Tickets");
        SupportTickets.setPreferredSize(new java.awt.Dimension(262, 43));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        HeaderPanel.add(SupportTickets, gridBagConstraints);

        jLabel3.setBackground(new java.awt.Color(229, 192, 123));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("jLabel3");
        jLabel3.setPreferredSize(new java.awt.Dimension(85, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        HeaderPanel.add(jLabel3, gridBagConstraints);

        add(HeaderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 100));

        jScrollPane1.setBackground(new java.awt.Color(48, 48, 46));
        jScrollPane1.setForeground(new java.awt.Color(43, 43, 43));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 500));

        TableContent.setBackground(new java.awt.Color(43, 43, 43));
        TableContent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "User", "Issue", "Priority", "Submitted", "Action"
            }
        ));
        TableContent.setShowVerticalLines(false);
        jScrollPane1.setViewportView(TableContent);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 950, 460));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JLabel SupportTickets;
    private javax.swing.JTable TableContent;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
