/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carrentalsystem.ui.admin;

/**
 *
 * @author EMY2025
 */
public class TicketRow extends javax.swing.JPanel {

    
    public TicketRow() {
        initComponents();
    }
    
    public void setTicketInfo(String initial, String subject, String subtext, String priority) {
    AvatarLabel.setText(initial);
    SubjectLabel.setText(subject);
    UserLabel.setText(subtext);
    PriorityLabel.setText(priority);
    
    // Simple logic for priority colors
    if(priority.equalsIgnoreCase("High")) {
        PriorityLabel.setForeground(new java.awt.Color(255, 100, 100)); // Reddish
    } else if(priority.equalsIgnoreCase("Med")) {
        PriorityLabel.setForeground(new java.awt.Color(255, 200, 100)); // Orange-ish
    } else {
        PriorityLabel.setForeground(new java.awt.Color(150, 255, 150)); // Greenish
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AvatarLabel = new javax.swing.JLabel();
        SubjectLabel = new javax.swing.JLabel();
        UserLabel = new javax.swing.JLabel();
        PriorityLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(48, 48, 46));

        AvatarLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        AvatarLabel.setForeground(new java.awt.Color(0, 102, 204));
        AvatarLabel.setText("JD");

        SubjectLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SubjectLabel.setForeground(new java.awt.Color(255, 255, 255));
        SubjectLabel.setText("Car not returned on time");

        UserLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        UserLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel.setText("Juan Dela Cruz");

        PriorityLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PriorityLabel.setForeground(new java.awt.Color(204, 0, 0));
        PriorityLabel.setText("HIGH");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(AvatarLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SubjectLabel)
                    .addComponent(UserLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(PriorityLabel)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PriorityLabel)
                    .addComponent(AvatarLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SubjectLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UserLabel)))
                .addContainerGap(227, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AvatarLabel;
    private javax.swing.JLabel PriorityLabel;
    private javax.swing.JLabel SubjectLabel;
    private javax.swing.JLabel UserLabel;
    // End of variables declaration//GEN-END:variables
}
