/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carrentalsystem.ui.admin;

/**
 *
 * @author EMY2025
 */
import java.awt.*;
import java.util.Map;
public class TypeChart extends javax.swing.JPanel {
    private Map<String, Integer> carData;
    
    // This method accepts the user's dynamic data
    public void setChartData(Map<String, Integer> data) {
        this.carData = data;
        repaint(); // Forces the panel to redraw whenever data changes
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (carData == null || carData.isEmpty()) return;

        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        
        int panelWidth = getWidth();
        int panelHeight = getHeight();
        int barWidth = 40;
        int spacing = (panelWidth - (carData.size() * barWidth)) / (carData.size() + 1);
        int maxVal = carData.values().stream().max(Integer::compare).get();

        int x = spacing;
        for (Map.Entry<String, Integer> entry : carData.entrySet()) {
            // Calculate height relative to the highest count
            int barHeight = (entry.getValue() * (panelHeight - 100)) / maxVal;
            
            // Draw the bar using your theme's green color
            g2.setColor(new Color(11, 213, 91)); 
            g2.fillRect(x, panelHeight - barHeight - 40, barWidth, barHeight);

            // Draw the car type name (Dynamic based on user input)
            g2.setColor(Color.WHITE);
            g2.drawString(entry.getKey(), x, panelHeight - 20);
            
            // Draw the numerical value above the bar
            g2.drawString(entry.getValue().toString(), x + (barWidth / 4), panelHeight - barHeight - 45);

            x += barWidth + spacing; // Moves to the next position dynamically
        }
    }

    
    public TypeChart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
