/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrentalsystem.ui.admin;

import carrentalsystem.auth.LoginFrame;
/**
 *
 * @author macbookairm1grey
 */
import javax.swing.ImageIcon;
import java.awt.Image;

public class ViewButtonPanel extends javax.swing.JFrame {
    
    private ApprovalQueuePanel approvalPanel = new ApprovalQueuePanel();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewButtonPanel.class.getName());
    // Add this at the top of your class variables
    private java.util.List<carrentalsystem.models.Car> userCarList = new java.util.ArrayList<>();
    private String planStatus = "Free";

    /**
     * Creates new form AdminDashboard
     */
    public ViewButtonPanel() {
        initComponents();
        jPanel1.add(approvalPanel);
        approvalPanel.setBounds(50, 250, 800, 400); // Adjust X, Y, W, H to fit your design
        approvalPanel.setVisible(false); // Hide it by default
        btnProfileInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
        switchPanel(evt);
    }
});
        
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

        //Position Top Bar Icons
        TopBarPanel.add(ProfileIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 20, 50, 50));
        TopBarPanel.add(NotifyIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 20, 50, 50));

        // Add this to your constructor after initComponents()
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                int width = getWidth();
                // Position Profile 70 pixels from the right edge
                ProfileIcon.setLocation(width - 90, ProfileIcon.getY());
                // Position Notify 140 pixels from the right edge
                NotifyIcon.setLocation(width - 160, NotifyIcon.getY());
            }
        });

        // The "Easy Way" - One line per icon
        setIcon(OverviewIcon, "/carrentalsystem/ui/admin/PIC/four-squares.png", 35, 35);
        setIcon(ListingIcon, "/carrentalsystem/ui/admin/PIC/Listing.png", 35, 35);
        setIcon(UsersIcon, "/carrentalsystem/ui/admin/PIC/Users.png", 35, 35);
        setIcon(BookingsIcon1, "/carrentalsystem/ui/admin/PIC/Bookings.png", 35, 35);
        setIcon(SupportIcon, "/carrentalsystem/ui/admin/PIC/support.png", 35, 35);
        setIcon(SettingsIcon, "/carrentalsystem/ui/admin/PIC/setting (1).png", 35, 35);
        setIcon(LogoutIcon, "/carrentalsystem/ui/admin/PIC/logout-white.png", 35, 35);
        //Top Bar Panel Icon
        setIcon(ProfileIcon, "/carrentalsystem/ui/admin/PIC/Profile.png", 50, 50);
        setIcon(NotifyIcon, "/carrentalsystem/ui/admin/PIC/bell.png", 50, 50);
    }

    private void setIcon(javax.swing.JLabel label, String path, int width, int height) {
        try {
            java.net.URL imgURL = getClass().getResource(path);
            if (imgURL != null) {
                ImageIcon icon = new ImageIcon(imgURL);
                // Now uses the width and height parameters you pass in
                Image img = icon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
                label.setIcon(new ImageIcon(img));
            }
        } catch (Exception e) {
            System.err.println("Could not load image: " + path);
        }
    }
    
    public void updateSubscriptionBadge(String plan) {
    // If jPanel3 is created as an anonymous class, you may need a field 
    // to store the status and then call repaint()
    this.planStatus = plan; 
    Membershiplbl.repaint();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopBarPanel = new javax.swing.JPanel();
        CarRental = new javax.swing.JLabel();
        ProfileIcon = new javax.swing.JLabel();
        NotifyIcon = new javax.swing.JLabel();
        sideBarPanel = new javax.swing.JPanel();
        Main1 = new javax.swing.JLabel();
        Admin = new javax.swing.JLabel();
        OverviewIcon = new javax.swing.JLabel();
        OverviewButton = new javax.swing.JButton();
        ListingIcon = new javax.swing.JLabel();
        UsersIcon = new javax.swing.JLabel();
        UsersButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        BookingsIcon1 = new javax.swing.JLabel();
        BookingsButton = new javax.swing.JButton();
        SupportIcon = new javax.swing.JLabel();
        SupportButton = new javax.swing.JButton();
        SettingsIcon = new javax.swing.JLabel();
        SettingsButton = new javax.swing.JButton();
        LogoutIcon = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JButton();
        ListingButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblUserDetails = new javax.swing.JLabel();
        usersNamelbl = new javax.swing.JLabel();
        Membershiplbl = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                // Ensure the panel itself doesn't draw a background square
                super.paintComponent(g); 

                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                int w = getWidth();
                int h = getHeight();

                // 1. DYNAMIC COLOR: Changes based on planStatus
                if (planStatus.equalsIgnoreCase("Free")) {
                    g2.setColor(new java.awt.Color(255, 245, 200)); // Light Yellow
                } else {
                    g2.setColor(new java.awt.Color(200, 230, 255)); // Light Blue
                }

                // 2. DRAW PILL SHAPE
                g2.fillRoundRect(0, 0, w, h, h, h);

                // 3. TEXT SETTINGS: Increased to 14pt Bold
                g2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));

                if (planStatus.equalsIgnoreCase("Free")) {
                    g2.setColor(new java.awt.Color(139, 128, 0)); // Dark Gold/Brown text
                    drawCenteredString(g2, "Free", w, h);
                } else {
                    g2.setColor(new java.awt.Color(0, 102, 204)); // Dark Blue text
                    drawCenteredString(g2, "Pro", w, h);
                }

                g2.dispose();
            }

            // Helper method to keep text perfectly centered regardless of font size
            private void drawCenteredString(java.awt.Graphics2D g2, String text, int w, int h) {
                java.awt.FontMetrics fm = g2.getFontMetrics();
                int x = (w - fm.stringWidth(text)) / 2;
                int y = ((h - fm.getHeight()) / 2) + fm.getAscent();
                g2.drawString(text, x, y);
            }
        };
        btnSaveChanges = new javax.swing.JButton() {
            // Variable to track click state
            private boolean isPressed = false;

            {
                // Add listeners so the button "reacts" to you
                addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mousePressed(java.awt.event.MouseEvent e) { isPressed = true; repaint(); }
                    public void mouseReleased(java.awt.event.MouseEvent e) { isPressed = false; repaint(); }
                });
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                int w = getWidth();
                int h = getHeight();
                int round = 15;

                // 1. THE OUTER SHADOW (Drawn first)
                // We shift this down by 4 pixels to make it look like it's floating
                g2.setColor(new java.awt.Color(0, 0, 0, 60)); 
                g2.fillRoundRect(3, 5, w - 6, h - 8, round, round);

                // 2. THE BUTTON BODY (Solid Color)
                // If pressed, we make it slightly darker to give a "click" feel
                if (isPressed) {
                    g2.setColor(new java.awt.Color(45, 45, 45)); // Darker when clicked
                } else {
                    g2.setColor(new java.awt.Color(70, 70, 70)); // Normal solid grey
                }

                // We draw the body slightly higher than the shadow
                g2.fillRoundRect(2, 2, w - 6, h - 8, round, round);

                // 3. THE TEXT
                g2.setColor(java.awt.Color.WHITE);
                g2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 18));
                java.awt.FontMetrics fm = g2.getFontMetrics();
                int x = ((w - 6) - fm.stringWidth(getText())) / 2 + 2;
                int y = ((h - 8) + fm.getAscent() - fm.getDescent()) / 2 + 2;

                g2.drawString(getText(), x, y);
                g2.dispose();
            }
        };
        btnArchiveUser = new javax.swing.JButton() {
            private boolean isPressed = false;

            {
                // Maintains the clickable interaction
                addMouseListener(new java.awt.event.MouseAdapter() {
                    @Override
                    public void mousePressed(java.awt.event.MouseEvent e) { isPressed = true; repaint(); }
                    @Override
                    public void mouseReleased(java.awt.event.MouseEvent e) { isPressed = false; repaint(); }
                });
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                int w = getWidth();
                int h = getHeight();
                int round = 15;

                // 1. CLICK FEEDBACK (Optional)
                // If you want a subtle hint that it's being pressed, we can draw a 
                // very faint tint. If you want it TOTALY transparent, delete these 3 lines.
                if (isPressed) {
                    g2.setColor(new java.awt.Color(255, 255, 255, 10)); // Ultra-faint white tint
                    g2.fillRoundRect(2, 2, w - 5, h - 5, round, round);
                }

                // 2. BORDER (Solid Grey 153, 153, 153)
                g2.setColor(new java.awt.Color(153, 153, 153));
                g2.setStroke(new java.awt.BasicStroke(1.2f));
                g2.drawRoundRect(2, 2, w - 5, h - 5, round, round);

                // 3. TEXT
                g2.setColor(new java.awt.Color(230, 230, 230));
                g2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 18));
                java.awt.FontMetrics fm = g2.getFontMetrics();
                int x = ((w - 5) - fm.stringWidth(getText())) / 2 + 2;
                int y = ((h - 5) + fm.getAscent() - fm.getDescent()) / 2 + 2;

                g2.drawString(getText(), x, y);
                g2.dispose();
            }
        };
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(3, 33, 33));

        TopBarPanel.setBackground(new java.awt.Color(30, 30, 30));
        TopBarPanel.setPreferredSize(new java.awt.Dimension(1290, 90));
        TopBarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CarRental.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        CarRental.setForeground(new java.awt.Color(255, 255, 255));
        CarRental.setText("Rent A Car");
        TopBarPanel.add(CarRental, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        ProfileIcon.setPreferredSize(new java.awt.Dimension(20, 90));
        TopBarPanel.add(ProfileIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 10, 80, 70));

        NotifyIcon.setPreferredSize(new java.awt.Dimension(20, 90));
        TopBarPanel.add(NotifyIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, 90, 60));

        getContentPane().add(TopBarPanel, java.awt.BorderLayout.NORTH);

        sideBarPanel.setBackground(new java.awt.Color(38, 38, 36));
        sideBarPanel.setMinimumSize(new java.awt.Dimension(300, 485));
        sideBarPanel.setPreferredSize(new java.awt.Dimension(353, 700));
        sideBarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Main1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Main1.setForeground(new java.awt.Color(255, 255, 255));
        Main1.setText("MAIN");
        sideBarPanel.add(Main1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        Admin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Admin.setForeground(new java.awt.Color(255, 255, 255));
        Admin.setText("ADMIN");
        sideBarPanel.add(Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        OverviewIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBarPanel.add(OverviewIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 35, 35));

        OverviewButton.setBackground(new java.awt.Color(38, 38, 36));
        OverviewButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        OverviewButton.setForeground(new java.awt.Color(255, 255, 255));
        OverviewButton.setText("Overview");
        OverviewButton.setBorder(null);
        OverviewButton.setBorderPainted(false);
        OverviewButton.setContentAreaFilled(false);
        OverviewButton.setFocusPainted(false);
        OverviewButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        OverviewButton.setPreferredSize(new java.awt.Dimension(270, 50));
        sideBarPanel.add(OverviewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        ListingIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBarPanel.add(ListingIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 35, 35));

        UsersIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBarPanel.add(UsersIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 35, 35));

        UsersButton.setBackground(new java.awt.Color(48, 48, 46));
        UsersButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        UsersButton.setForeground(new java.awt.Color(255, 255, 255));
        UsersButton.setText("Users");
        UsersButton.setBorder(null);
        UsersButton.setBorderPainted(false);
        UsersButton.setContentAreaFilled(false);
        UsersButton.setFocusPainted(false);
        UsersButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        UsersButton.setPreferredSize(new java.awt.Dimension(270, 50));
        sideBarPanel.add(UsersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jPanel2.setBackground(new java.awt.Color(48, 48, 46));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        sideBarPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 360, 50));

        BookingsIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBarPanel.add(BookingsIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 35, 35));

        BookingsButton.setBackground(new java.awt.Color(48, 48, 46));
        BookingsButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BookingsButton.setForeground(new java.awt.Color(255, 255, 255));
        BookingsButton.setText("Bookings");
        BookingsButton.setBorder(null);
        BookingsButton.setBorderPainted(false);
        BookingsButton.setContentAreaFilled(false);
        BookingsButton.setFocusPainted(false);
        BookingsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BookingsButton.setPreferredSize(new java.awt.Dimension(270, 50));
        sideBarPanel.add(BookingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 270, -1));

        SupportIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBarPanel.add(SupportIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 35, 35));

        SupportButton.setBackground(new java.awt.Color(48, 48, 46));
        SupportButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        SupportButton.setForeground(new java.awt.Color(255, 255, 255));
        SupportButton.setText("Support");
        SupportButton.setBorder(null);
        SupportButton.setBorderPainted(false);
        SupportButton.setContentAreaFilled(false);
        SupportButton.setFocusPainted(false);
        SupportButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SupportButton.setPreferredSize(new java.awt.Dimension(270, 50));
        sideBarPanel.add(SupportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        SettingsIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBarPanel.add(SettingsIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 35, 35));

        SettingsButton.setBackground(new java.awt.Color(48, 48, 46));
        SettingsButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        SettingsButton.setForeground(new java.awt.Color(255, 255, 255));
        SettingsButton.setText("Settings");
        SettingsButton.setBorder(null);
        SettingsButton.setBorderPainted(false);
        SettingsButton.setContentAreaFilled(false);
        SettingsButton.setFocusPainted(false);
        SettingsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SettingsButton.setPreferredSize(new java.awt.Dimension(270, 50));
        sideBarPanel.add(SettingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        LogoutIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBarPanel.add(LogoutIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 35, 35));

        LogoutButton.setBackground(new java.awt.Color(48, 48, 46));
        LogoutButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogoutButton.setText("Logout");
        LogoutButton.setBorder(null);
        LogoutButton.setBorderPainted(false);
        LogoutButton.setContentAreaFilled(false);
        LogoutButton.setFocusPainted(false);
        LogoutButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LogoutButton.setPreferredSize(new java.awt.Dimension(270, 50));
        sideBarPanel.add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        ListingButton.setBackground(new java.awt.Color(48, 48, 46));
        ListingButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ListingButton.setForeground(new java.awt.Color(255, 255, 255));
        ListingButton.setText("Listing");
        ListingButton.setBorder(null);
        ListingButton.setBorderPainted(false);
        ListingButton.setContentAreaFilled(false);
        ListingButton.setFocusPainted(false);
        ListingButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ListingButton.setPreferredSize(new java.awt.Dimension(270, 50));
        sideBarPanel.add(ListingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        getContentPane().add(sideBarPanel, java.awt.BorderLayout.WEST);

        jPanel1.setBackground(new java.awt.Color(48, 48, 46));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUserDetails.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        lblUserDetails.setForeground(new java.awt.Color(255, 255, 255));
        lblUserDetails.setText("User Details");
        jPanel1.add(lblUserDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        usersNamelbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        usersNamelbl.setForeground(new java.awt.Color(204, 204, 204));
        usersNamelbl.setPreferredSize(new java.awt.Dimension(400, 32));
        jPanel1.add(usersNamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        Membershiplbl.setBackground(new java.awt.Color(48, 48, 46));
        Membershiplbl.setForeground(new java.awt.Color(48, 48, 46));
        Membershiplbl.setOpaque(false);
        Membershiplbl.setPreferredSize(new java.awt.Dimension(100, 30));

        javax.swing.GroupLayout MembershiplblLayout = new javax.swing.GroupLayout(Membershiplbl);
        Membershiplbl.setLayout(MembershiplblLayout);
        MembershiplblLayout.setHorizontalGroup(
            MembershiplblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        MembershiplblLayout.setVerticalGroup(
            MembershiplblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(Membershiplbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        btnSaveChanges.setBackground(new java.awt.Color(48, 48, 46));
        btnSaveChanges.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSaveChanges.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveChanges.setText("Save Changes");
        btnSaveChanges.setBorderPainted(false);
        btnSaveChanges.setContentAreaFilled(false);
        btnSaveChanges.setFocusPainted(false);
        btnSaveChanges.setPreferredSize(new java.awt.Dimension(163, 53));
        jPanel1.add(btnSaveChanges, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, -1));

        btnArchiveUser.setBackground(new java.awt.Color(48, 48, 46));
        btnArchiveUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnArchiveUser.setForeground(new java.awt.Color(153, 153, 153));
        btnArchiveUser.setText("Archive User");
        btnArchiveUser.setBorder(null);
        btnArchiveUser.setBorderPainted(false);
        btnArchiveUser.setContentAreaFilled(false);
        btnArchiveUser.setOpaque(false);
        btnArchiveUser.setPreferredSize(new java.awt.Dimension(120, 45));
        jPanel1.add(btnArchiveUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 90, -1, -1));

        jSeparator1.setPreferredSize(new java.awt.Dimension(950, 10));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewButtonPanel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin;
    private javax.swing.JButton BookingsButton;
    private javax.swing.JLabel BookingsIcon1;
    private javax.swing.JLabel CarRental;
    private javax.swing.JButton ListingButton;
    private javax.swing.JLabel ListingIcon;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JLabel LogoutIcon;
    private javax.swing.JLabel Main1;
    private javax.swing.JPanel Membershiplbl;
    private javax.swing.JLabel NotifyIcon;
    private javax.swing.JButton OverviewButton;
    private javax.swing.JLabel OverviewIcon;
    private javax.swing.JLabel ProfileIcon;
    private javax.swing.JButton SettingsButton;
    private javax.swing.JLabel SettingsIcon;
    private javax.swing.JButton SupportButton;
    private javax.swing.JLabel SupportIcon;
    private javax.swing.JPanel TopBarPanel;
    private javax.swing.JButton UsersButton;
    private javax.swing.JLabel UsersIcon;
    private javax.swing.JButton btnArchiveUser;
    private javax.swing.JButton btnSaveChanges;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblUserDetails;
    private javax.swing.JPanel sideBarPanel;
    private javax.swing.JLabel usersNamelbl;
    // End of variables declaration//GEN-END:variables
}
