/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrentalsystem.ui.admin;

import carrentalsystem.auth.LoginFrame;
/**
 *
 * @author macbookairm1grey
 */
import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.util.Map;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.Vector;
import javax.swing.JTextField;

public class ViewButtonPanel extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewButtonPanel.class.getName());
    // Add this at the top of your class variables
    private java.util.List<carrentalsystem.models.Car> userCarList = new java.util.ArrayList<>();
    private String planStatus = "False";

    /**
     * Creates new form AdminDashboard
     */
    public ViewButtonPanel() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

        //Position Top Bar Icons
        TopBarPanel.add(ProfileIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 20, 50, 50));
        TopBarPanel.add(NotifyIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 20, 50, 50));

        // Add this to your constructor after initComponents()
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                int width = getWidth();
                // Position Profile 70 pixels from the right edge
                ProfileIcon.setLocation(width - 90, ProfileIcon.getY());
                // Position Notify 140 pixels from the right edge
                NotifyIcon.setLocation(width - 160, NotifyIcon.getY());
            }
        });

        // The "Easy Way" - One line per icon
        setIcon(OverviewIcon, "/carrentalsystem/ui/admin/PIC/four-squares.png", 35, 35);
        setIcon(ListingIcon, "/carrentalsystem/ui/admin/PIC/Listing.png", 35, 35);
        setIcon(UsersIcon, "/carrentalsystem/ui/admin/PIC/Users.png", 35, 35);
        setIcon(BookingsIcon1, "/carrentalsystem/ui/admin/PIC/Bookings.png", 35, 35);
        setIcon(SupportIcon, "/carrentalsystem/ui/admin/PIC/support.png", 35, 35);
        setIcon(SettingsIcon, "/carrentalsystem/ui/admin/PIC/setting (1).png", 35, 35);
        setIcon(LogoutIcon, "/carrentalsystem/ui/admin/PIC/logout-white.png", 35, 35);
        //Top Bar Panel Icon
        setIcon(ProfileIcon, "/carrentalsystem/ui/admin/PIC/Profile.png", 50, 50);
        setIcon(NotifyIcon, "/carrentalsystem/ui/admin/PIC/bell.png", 50, 50);
    }

    private void setIcon(javax.swing.JLabel label, String path, int width, int height) {
        try {
            java.net.URL imgURL = getClass().getResource(path);
            if (imgURL != null) {
                ImageIcon icon = new ImageIcon(imgURL);
                // Now uses the width and height parameters you pass in
                Image img = icon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
                label.setIcon(new ImageIcon(img));
            }
        } catch (Exception e) {
            System.err.println("Could not load image: " + path);
        }
    }
    
    public void updateSubscriptionBadge(String status) {
    this.planStatus = status;
    
    if ("Free".equalsIgnoreCase(status)) {
        lblStatusText.setText("Free");
        lblStatusText.setForeground(new java.awt.Color(120, 100, 0)); // Brown
    } else {
        lblStatusText.setText("Pro");
        lblStatusText.setForeground(new java.awt.Color(0, 50, 150)); // Dark Blue
    }
    
    membershipBagde.repaint(); // Force the background to redraw
}
    // Your classmate can use this method to update the count dynamically
    public void updateActiveListingCount(int count) {
    lblListingCount.setText("(" + count + ")");
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopBarPanel = new javax.swing.JPanel();
        CarRental = new javax.swing.JLabel();
        ProfileIcon = new javax.swing.JLabel();
        NotifyIcon = new javax.swing.JLabel();
        sideBarPanel = new javax.swing.JPanel();
        Main1 = new javax.swing.JLabel();
        Admin = new javax.swing.JLabel();
        OverviewIcon = new javax.swing.JLabel();
        OverviewButton = new javax.swing.JButton();
        buttonArchiveUser = new javax.swing.JButton();
        ListingIcon = new javax.swing.JLabel();
        ListingButton = new javax.swing.JButton();
        UsersIcon = new javax.swing.JLabel();
        UsersButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        BookingsIcon1 = new javax.swing.JLabel();
        BookingsButton = new javax.swing.JButton();
        SupportIcon = new javax.swing.JLabel();
        SupportButton = new javax.swing.JButton();
        SettingsIcon = new javax.swing.JLabel();
        SettingsButton = new javax.swing.JButton();
        LogoutIcon = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblUserDetails = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        membershipBagde = // Corrected initialization
        membershipBagde = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g); // Call super
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, 
                    java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                int w = getWidth();
                int h = getHeight();

                // Check the data from your planStatus variable
                if ("Free".equalsIgnoreCase(planStatus)) {
                    g2.setColor(new java.awt.Color(255, 245, 200)); // Light Yellow
                    lblStatusText.setText("Free");
                    lblStatusText.setForeground(new java.awt.Color(120, 100, 0)); // Brown
                } else if ("Pro".equalsIgnoreCase(planStatus)) {
                    g2.setColor(new java.awt.Color(200, 230, 255)); // Light Blue
                    lblStatusText.setText("Pro");
                    lblStatusText.setForeground(new java.awt.Color(0, 50, 150)); // Dark Blue
                }

                g2.fillRoundRect(0, 0, w, h, h, h);
                g2.dispose();
            }
        };
        // Set to transparent so the rounded corners show correctly
        membershipBagde.setOpaque(false);
        lblStatusText = new javax.swing.JLabel();
        buttonSaveChanges1 = // Set the drop-down to "Custom Creation"
        buttonArchiveUser = new javax.swing.JButton() {
            private int shadowGap = 3;

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, 
                    java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                int w = getWidth();
                int h = getHeight() - shadowGap;

                // 1. Draw Solid Shadow (Darker than background)
                g2.setColor(new java.awt.Color(0, 0, 0, 60)); 
                g2.fillRoundRect(0, shadowGap, w, h, 10, 10);

                // 2. Draw Solid Button Body
                if (getModel().isPressed()) {
                    g2.setColor(new java.awt.Color(90, 90, 90)); // Pressed color
                    g2.fillRoundRect(0, shadowGap, w, h, 10, 10); // Shift body down
                } else {
                    g2.setColor(new java.awt.Color(110, 110, 110)); // Normal solid color
                    g2.fillRoundRect(0, 0, w, h, 10, 10);
                }

                // 3. Draw Text Manually (to ensure it stays centered)
                g2.setColor(java.awt.Color.WHITE);
                g2.setFont(getFont());
                java.awt.FontMetrics fm = g2.getFontMetrics();
                int textX = (w - fm.stringWidth(getText())) / 2;
                int textY = (h - fm.getHeight()) / 2 + fm.getAscent() + (getModel().isPressed() ? shadowGap : 0);
                g2.drawString(getText(), textX, textY);

                g2.dispose();
            }
        };
        activeListingHeader = new javax.swing.JPanel();
        lblActiveListing = new javax.swing.JLabel();
        lblListingCount = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlCarCard = pnlCarCard = new javax.swing.JPanel() {
            private int cornerRadius = 20; // Adjust for smoothness [cite: 1]
            private java.awt.Color borderColor = new java.awt.Color(204, 204, 204); // Lighter gray for border [cite: 9]

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g); // Call super to ensure children are painted correctly
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, 
                    java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                int w = getWidth();
                int h = getHeight();

                // Fill background with card color (overrides standard background) [cite: 9]
                g2.setColor(getBackground());
                g2.fillRoundRect(0, 0, w, h, cornerRadius, cornerRadius);

                // Draw the thin, light gray rounded border [cite: 9]
                g2.setColor(borderColor);
                g2.setStroke(new java.awt.BasicStroke(1f)); // Thin border [cite: 9]
                g2.drawRoundRect(0, 0, w - 1, h - 1, cornerRadius, cornerRadius);

                g2.dispose();
            }
        };
        // Critical setup after creation
        pnlCarCard.setOpaque(false); // Let the custom drawing handle the background [cite: 1];
        pnlCarImageContainer = new javax.swing.JPanel();
        lblCarImage = lblCarImage = new javax.swing.JLabel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, 
                    java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // Create a rounded clip area
                java.awt.geom.RoundRectangle2D roundedRect = new java.awt.geom.RoundRectangle2D.Float(
                    0, 0, getWidth(), getHeight(), 20, 20); // 20 is the corner radius
                g2.clip(roundedRect);

                super.paintComponent(g2);
                g2.dispose();
            }
        };
        pnlCarTextDetails = new javax.swing.JPanel();
        lblCarName = new javax.swing.JLabel();
        CurrentLocation = new javax.swing.JLabel();
        lblCarLocation = new javax.swing.JLabel();
        CurrentStatus = new javax.swing.JLabel();
        lblCarStatus = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPreviousBookings = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(3, 33, 33));

        TopBarPanel.setBackground(new java.awt.Color(30, 30, 30));
        TopBarPanel.setPreferredSize(new java.awt.Dimension(1290, 90));
        TopBarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CarRental.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        CarRental.setForeground(new java.awt.Color(255, 255, 255));
        CarRental.setText("Rent A Car");
        TopBarPanel.add(CarRental, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        ProfileIcon.setPreferredSize(new java.awt.Dimension(20, 90));
        TopBarPanel.add(ProfileIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 10, 80, 70));

        NotifyIcon.setPreferredSize(new java.awt.Dimension(20, 90));
        TopBarPanel.add(NotifyIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, 90, 60));

        getContentPane().add(TopBarPanel, java.awt.BorderLayout.NORTH);

        sideBarPanel.setBackground(new java.awt.Color(38, 38, 36));
        sideBarPanel.setMinimumSize(new java.awt.Dimension(300, 485));
        sideBarPanel.setPreferredSize(new java.awt.Dimension(353, 700));
        sideBarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Main1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Main1.setForeground(new java.awt.Color(255, 255, 255));
        Main1.setText("MAIN");
        sideBarPanel.add(Main1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        Admin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Admin.setForeground(new java.awt.Color(255, 255, 255));
        Admin.setText("ADMIN");
        sideBarPanel.add(Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        OverviewIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBarPanel.add(OverviewIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 35, 35));

        OverviewButton.setBackground(new java.awt.Color(38, 38, 36));
        OverviewButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        OverviewButton.setForeground(new java.awt.Color(255, 255, 255));
        OverviewButton.setText("Overview");
        OverviewButton.setBorder(null);
        OverviewButton.setBorderPainted(false);
        OverviewButton.setContentAreaFilled(false);
        OverviewButton.setFocusPainted(false);
        OverviewButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        OverviewButton.setPreferredSize(new java.awt.Dimension(270, 50));
        sideBarPanel.add(OverviewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        buttonArchiveUser.setBackground(new java.awt.Color(48, 48, 46));

        buttonArchiveUser.setFont(new java.awt.Font("Segoe UI", 0, 18));

        buttonArchiveUser.setForeground(new java.awt.Color(204, 204, 204));

        buttonArchiveUser.setText("Archive User");

        buttonArchiveUser.setBorderPainted(false);

        buttonArchiveUser.setContentAreaFilled(false);

        buttonArchiveUser.setFocusPainted(false);

        buttonArchiveUser.setPreferredSize(new java.awt.Dimension(150, 43));
        sideBarPanel.add(buttonArchiveUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, -1, -1));

        ListingIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBarPanel.add(ListingIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 35, 35));

        ListingButton.setBackground(new java.awt.Color(48, 48, 46));
        ListingButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ListingButton.setForeground(new java.awt.Color(255, 255, 255));
        ListingButton.setText("Listing");
        ListingButton.setBorder(null);
        ListingButton.setBorderPainted(false);
        ListingButton.setContentAreaFilled(false);
        ListingButton.setFocusPainted(false);
        ListingButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ListingButton.setPreferredSize(new java.awt.Dimension(270, 50));
        sideBarPanel.add(ListingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        UsersIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBarPanel.add(UsersIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 35, 35));

        UsersButton.setBackground(new java.awt.Color(48, 48, 46));
        UsersButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        UsersButton.setForeground(new java.awt.Color(255, 255, 255));
        UsersButton.setText("Users");
        UsersButton.setBorder(null);
        UsersButton.setBorderPainted(false);
        UsersButton.setContentAreaFilled(false);
        UsersButton.setFocusPainted(false);
        UsersButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        UsersButton.setPreferredSize(new java.awt.Dimension(270, 50));
        sideBarPanel.add(UsersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jPanel2.setBackground(new java.awt.Color(48, 48, 46));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        sideBarPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 360, 50));

        BookingsIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBarPanel.add(BookingsIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 35, 35));

        BookingsButton.setBackground(new java.awt.Color(48, 48, 46));
        BookingsButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BookingsButton.setForeground(new java.awt.Color(255, 255, 255));
        BookingsButton.setText("Bookings");
        BookingsButton.setBorder(null);
        BookingsButton.setBorderPainted(false);
        BookingsButton.setContentAreaFilled(false);
        BookingsButton.setFocusPainted(false);
        BookingsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BookingsButton.setPreferredSize(new java.awt.Dimension(270, 50));
        sideBarPanel.add(BookingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 270, -1));

        SupportIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBarPanel.add(SupportIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 35, 35));

        SupportButton.setBackground(new java.awt.Color(48, 48, 46));
        SupportButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        SupportButton.setForeground(new java.awt.Color(255, 255, 255));
        SupportButton.setText("Support");
        SupportButton.setBorder(null);
        SupportButton.setBorderPainted(false);
        SupportButton.setContentAreaFilled(false);
        SupportButton.setFocusPainted(false);
        SupportButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SupportButton.setPreferredSize(new java.awt.Dimension(270, 50));
        sideBarPanel.add(SupportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        SettingsIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBarPanel.add(SettingsIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 35, 35));

        SettingsButton.setBackground(new java.awt.Color(48, 48, 46));
        SettingsButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        SettingsButton.setForeground(new java.awt.Color(255, 255, 255));
        SettingsButton.setText("Settings");
        SettingsButton.setBorder(null);
        SettingsButton.setBorderPainted(false);
        SettingsButton.setContentAreaFilled(false);
        SettingsButton.setFocusPainted(false);
        SettingsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SettingsButton.setPreferredSize(new java.awt.Dimension(270, 50));
        sideBarPanel.add(SettingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        LogoutIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBarPanel.add(LogoutIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 35, 35));

        LogoutButton.setBackground(new java.awt.Color(48, 48, 46));
        LogoutButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogoutButton.setText("Logout");
        LogoutButton.setBorder(null);
        LogoutButton.setBorderPainted(false);
        LogoutButton.setContentAreaFilled(false);
        LogoutButton.setFocusPainted(false);
        LogoutButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LogoutButton.setPreferredSize(new java.awt.Dimension(270, 50));
        sideBarPanel.add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        getContentPane().add(sideBarPanel, java.awt.BorderLayout.WEST);

        jPanel1.setBackground(new java.awt.Color(48, 48, 46));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUserDetails.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        lblUserDetails.setForeground(new java.awt.Color(255, 255, 255));
        lblUserDetails.setText("User Details");
        jPanel1.add(lblUserDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        lblUser.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setPreferredSize(new java.awt.Dimension(500, 43));
        jPanel1.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        membershipBagde.setOpaque(false);
        membershipBagde.setPreferredSize(new java.awt.Dimension(100, 35));

        lblStatusText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout membershipBagdeLayout = new javax.swing.GroupLayout(membershipBagde);
        membershipBagde.setLayout(membershipBagdeLayout);
        membershipBagdeLayout.setHorizontalGroup(
            membershipBagdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(membershipBagdeLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblStatusText, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        membershipBagdeLayout.setVerticalGroup(
            membershipBagdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, membershipBagdeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatusText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(membershipBagde, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        buttonSaveChanges1.setBackground(new java.awt.Color(48, 48, 46));
        buttonSaveChanges1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        buttonSaveChanges1.setForeground(new java.awt.Color(255, 255, 255));
        buttonSaveChanges1.setText("Save Changes");
        buttonSaveChanges1.setBorderPainted(false);
        buttonSaveChanges1.setContentAreaFilled(false);
        buttonSaveChanges1.setFocusPainted(false);
        buttonSaveChanges1.setPreferredSize(new java.awt.Dimension(200, 43));
        jPanel1.add(buttonSaveChanges1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, -1, -1));

        activeListingHeader.setBackground(new java.awt.Color(48, 48, 46));
        activeListingHeader.setOpaque(false);
        activeListingHeader.setPreferredSize(new java.awt.Dimension(215, 43));
        activeListingHeader.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblActiveListing.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblActiveListing.setForeground(new java.awt.Color(255, 255, 255));
        lblActiveListing.setText("Active Listings");
        activeListingHeader.add(lblActiveListing);

        lblListingCount.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblListingCount.setForeground(new java.awt.Color(255, 255, 255));
        lblListingCount.setText("( )");
        lblListingCount.setPreferredSize(new java.awt.Dimension(50, 32));
        activeListingHeader.add(lblListingCount);

        jPanel1.add(activeListingHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jSeparator1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 204, 204)));
        jSeparator1.setPreferredSize(new java.awt.Dimension(960, 2));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        pnlCarCard.setBackground(new java.awt.Color(46, 46, 46));
        pnlCarCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCarImageContainer.setOpaque(false);
        pnlCarImageContainer.setPreferredSize(new java.awt.Dimension(150, 100));
        pnlCarImageContainer.setLayout(new java.awt.GridBagLayout());

        lblCarImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCarImage.setPreferredSize(new java.awt.Dimension(150, 100));
        pnlCarImageContainer.add(lblCarImage, new java.awt.GridBagConstraints());

        pnlCarCard.add(pnlCarImageContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 110));

        pnlCarTextDetails.setOpaque(false);
        pnlCarTextDetails.setPreferredSize(new java.awt.Dimension(300, 100));
        pnlCarTextDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCarName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCarName.setForeground(new java.awt.Color(255, 255, 255));
        lblCarName.setPreferredSize(new java.awt.Dimension(127, 32));
        pnlCarTextDetails.add(lblCarName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, -1));

        CurrentLocation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CurrentLocation.setForeground(new java.awt.Color(204, 204, 204));
        CurrentLocation.setText("Current Location:");
        pnlCarTextDetails.add(CurrentLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, -1, -1));

        lblCarLocation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCarLocation.setForeground(new java.awt.Color(255, 255, 255));
        lblCarLocation.setPreferredSize(new java.awt.Dimension(135, 25));
        pnlCarTextDetails.add(lblCarLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 45, -1, -1));

        CurrentStatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CurrentStatus.setForeground(new java.awt.Color(204, 204, 204));
        CurrentStatus.setText("Current Status:");
        pnlCarTextDetails.add(CurrentStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        lblCarStatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCarStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblCarStatus.setPreferredSize(new java.awt.Dimension(135, 25));
        pnlCarTextDetails.add(lblCarStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        pnlCarCard.add(pnlCarTextDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 320, 110));

        jPanel1.add(pnlCarCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 500, 130));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Previous Bookings");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jSeparator2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jSeparator2.setPreferredSize(new java.awt.Dimension(960, 2));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 455, -1, -1));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(910, 200));
        // 1. Hide the background and the track of the scrollbar
        jScrollPane1.getVerticalScrollBar().setOpaque(false);
        jScrollPane1.getVerticalScrollBar().setBackground(new java.awt.Color(0, 0, 0, 0));

        // 2. Remove the border of the scrollbar itself
        jScrollPane1.getVerticalScrollBar().setBorder(null);
        jScrollPane1.getVerticalScrollBar().setPreferredSize(new java.awt.Dimension(0, 0));

        // 3. Make the "buttons" (the arrows at top/bottom) invisible or match background
        jScrollPane1.getVerticalScrollBar().setUI(new javax.swing.plaf.basic.BasicScrollBarUI() {
            @Override
            protected void configureScrollBarColors() {
                this.thumbColor = new java.awt.Color(100, 100, 100, 100); // Semi-transparent thumb
                this.trackColor = new java.awt.Color(0, 0, 0, 0);         // Fully transparent track
            }

            @Override
            protected javax.swing.JButton createDecreaseButton(int orientation) {
                return createZeroButton();
            }

            @Override
            protected javax.swing.JButton createIncreaseButton(int orientation) {
                return createZeroButton();
            }

            private javax.swing.JButton createZeroButton() {
                javax.swing.JButton jbutton = new javax.swing.JButton();
                jbutton.setPreferredSize(new java.awt.Dimension(0, 0));
                jbutton.setMinimumSize(new java.awt.Dimension(0, 0));
                jbutton.setMaximumSize(new java.awt.Dimension(0, 0));
                return jbutton;
            }
        });

        tblPreviousBookings.setBackground(new java.awt.Color(48, 48, 46));
        tblPreviousBookings.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tblPreviousBookings.setForeground(new java.awt.Color(255, 255, 255));
        tblPreviousBookings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Listing", "Dates", "Duration", "Total", "Payment Status"
            }
        ));
        tblPreviousBookings.setFillsViewportHeight(true);
        tblPreviousBookings.setGridColor(new java.awt.Color(255, 255, 255));
        tblPreviousBookings.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblPreviousBookings.setOpaque(false);
        tblPreviousBookings.setPreferredSize(new java.awt.Dimension(375, 64));
        tblPreviousBookings.setRowHeight(20);
        tblPreviousBookings.setShowVerticalLines(false);
        // 1. Set the Header background to your specific color (48, 48, 46)
        tblPreviousBookings.getTableHeader().setBackground(new java.awt.Color(48, 48, 46));
        tblPreviousBookings.getTableHeader().setOpaque(true); // Must be true to show the solid color

        // 2. Center-align the Header Text and set Font
        tblPreviousBookings.getTableHeader().setDefaultRenderer(new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {

                javax.swing.JLabel label = (javax.swing.JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                label.setHorizontalAlignment(javax.swing.JLabel.CENTER); // Center the text
                label.setBackground(new java.awt.Color(48, 48, 46));     // Apply your color here too
                label.setForeground(java.awt.Color.WHITE);              // Text color
                label.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 18));
                label.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.WHITE));

                return label;
            }
        });

        // 3. Fix the Header Height
        tblPreviousBookings.getTableHeader().setPreferredSize(new java.awt.Dimension(0, 40));

        // 1. Create a renderer that centers text AND sets the background color
        javax.swing.table.DefaultTableCellRenderer customRenderer = new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {

                java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                // Center the text
                ((javax.swing.JLabel)c).setHorizontalAlignment(javax.swing.JLabel.CENTER);

                // If the row is NOT selected, use your custom background
                if (!isSelected) {
                    c.setBackground(new java.awt.Color(48, 48, 46));
                }

                c.setForeground(java.awt.Color.WHITE);
                return c;
            }
        };

        // 2. Apply the renderer to all columns
        for (int i = 0; i < tblPreviousBookings.getColumnCount(); i++) {
            tblPreviousBookings.getColumnModel().getColumn(i).setCellRenderer(customRenderer);
        }

        // 3. Set the horizontal divider lines
        tblPreviousBookings.setShowHorizontalLines(true);
        tblPreviousBookings.setShowVerticalLines(false); // Clean list look
        tblPreviousBookings.setGridColor(new java.awt.Color(255, 255, 255, 50)); // Semi-transparent white line
        tblPreviousBookings.setRowHeight(40);
        tblPreviousBookings.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(tblPreviousBookings);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 960, 300));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewButtonPanel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin;
    private javax.swing.JButton BookingsButton;
    private javax.swing.JLabel BookingsIcon1;
    private javax.swing.JLabel CarRental;
    private javax.swing.JLabel CurrentLocation;
    private javax.swing.JLabel CurrentStatus;
    private javax.swing.JButton ListingButton;
    private javax.swing.JLabel ListingIcon;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JLabel LogoutIcon;
    private javax.swing.JLabel Main1;
    private javax.swing.JLabel NotifyIcon;
    private javax.swing.JButton OverviewButton;
    private javax.swing.JLabel OverviewIcon;
    private javax.swing.JLabel ProfileIcon;
    private javax.swing.JButton SettingsButton;
    private javax.swing.JLabel SettingsIcon;
    private javax.swing.JButton SupportButton;
    private javax.swing.JLabel SupportIcon;
    private javax.swing.JPanel TopBarPanel;
    private javax.swing.JButton UsersButton;
    private javax.swing.JLabel UsersIcon;
    private javax.swing.JPanel activeListingHeader;
    private javax.swing.JButton buttonArchiveUser;
    private javax.swing.JButton buttonSaveChanges1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblActiveListing;
    private javax.swing.JLabel lblCarImage;
    private javax.swing.JLabel lblCarLocation;
    private javax.swing.JLabel lblCarName;
    private javax.swing.JLabel lblCarStatus;
    private javax.swing.JLabel lblListingCount;
    private javax.swing.JLabel lblStatusText;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUserDetails;
    private javax.swing.JPanel membershipBagde;
    private javax.swing.JPanel pnlCarCard;
    private javax.swing.JPanel pnlCarImageContainer;
    private javax.swing.JPanel pnlCarTextDetails;
    private javax.swing.JPanel sideBarPanel;
    private javax.swing.JTable tblPreviousBookings;
    // End of variables declaration//GEN-END:variables
}
